### ISSUE TITLE
Add Source/Sample detail view

### ISSUE THREAD

**Issue by millercathy** [modc08/modc08#14]
@franksc Need to firm this up in doco

**Comment by franksc** [comment]
A basic source/sample view is [prototyped](https://github.com/modc08/mytardis/blob/0d3ed1a6fc1168875440155983cf1eab832df551/tardis/apps/acad/templates/source/detail.html) in MyTardis 'views' branch – it shows metadata about a sample and then a tabular view of all samples derived from the source.

**Comment by millercathy** [comment]
Hi @Li-ReDBox 
This issue is about creating a new view in MyTardis.
Each Source represented in the pipeline metadata shall have it's own page or view, where the metadata from the Source table is presented.
Below the Source metadata, the user will be able to view Samples derived from the Source. Because it is possible to have more than one Sample from a Source, there shall be tabs representing individual Sample records. Each Sample record shall display metadata of corresponding titles of related Datasets and the title shall be hyper linked to the Dataset view as outlined in #5.
The relevant metadata elements for this linking are in the metadata schema - @franksc can provide this if you need it.
Mock up attached as a guide.
![source sample view](https://cloud.githubusercontent.com/assets/9669002/6034823/abc16e1a-ac77-11e4-8e69-5cdd2e36089c.png)

**Comment by Li-ReDBox** [comment]
Merged commits from latest schematest: https://github.com/modc08/mytardis/commit/822ec7a081800b532fd3a8a8eeb481adbf3c82ac
Created sample dummy data.
Next working day: make it looks more like above mock-up.

**Comment by shundezhang** [comment]
This is done.

**Comment by franksc** [comment]
- If a dataset isn't accessible to the current user*, it shouldn't be linked to from a Source detail view

(\* e.g. end user is not logged in/anonymous, and dataset is not part of any public experiment)
- If a Source doesn't have _any_ datasets accessible to current user, it shouldn't be listed in the Source index view (or displayed on the map)

This is to prevent a) links appearing to datasets that an end user can't access b) sources appearing that don't link to any data the end user can access.

**Comment by shundezhang** [comment]
Done. Please test.

**Comment by franksc** [comment]
Testing:
- Datasets not accessible to current user not listed/linked to in Source view :white_check_mark: 
- If a Source has no datasets accessible to end user, it is not shown in Source index view :white_check_mark:

**Comment by franksc** [comment]
Closing this as view works as expected – only minor look-and-feel tweaks should be necessary from this point.
