### ISSUE TITLE
Add Source index view

### ISSUE THREAD

**Issue by millercathy** [modc08/modc08#15]

**Comment by millercathy** [comment]
In the first instance can we please implement functionality such that users can:
*Browse a list of Sources organised alphabetically by title... with each source linking to the Source view as outlined in #14 
*Browse a map where each Source is pinned/marked as identified by geoloc_lat and geoloc_long fields

**Comment by franksc** [comment]
@Li-ReDBox have a look at prototype view [here](https://github.com/modc08/mytardis/blob/0d3ed1a6fc1168875440155983cf1eab832df551/tardis/apps/acad/templates/source/index.html) in 'views' branch

The map stuff (using [Leaflet](http://leafletjs.com)) is commented out as it was rendering okay (I think) but not displaying on page – maybe some conflict with the MyTardis template CSS you can figure out ... (PS we are not wedded to using Leaflet)

**Comment by franksc** [comment]
Closing this as view works as expected – only minor look-and-feel tweaks should be necessary from this point.
