### ISSUE TITLE
Model experiment authors as standalone entities

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#18]
Experiments in MyTardis have one or more associated authors. Author names/details are recorded in association to a particular experiment (in Author_Experiment table, which has a foreign key relationship to Experiment) rather than independently, so if Author A is associated with five experiments you end up with five probably identical Author A records.

Also, author names are recorded in Author_Experiment in one field (e.g. 'Firstname Lastname'), which makes it a little tricky if you want to display as 'Lastname, Firstname' (or 'Lastname, Firstinitial' etc) in a citation or similar.

I propose adding a standalone Author model with separate fields for Firstname and Lastname, plus additional fields such as email address, institution (default=ACAD), ORCID, etc. Authors can be linked to experiments through a modified Author_Experiment model with fk's for Author and Experiment; the Author model can define this many-to-many relationship with Author through Author_Experiment, so no modification necessary to MyTardis Experiment model.

Modified Author_Experiment model can retain the 'order' field to record the position of a given author in the set of authors for the associated experiment.

If my Django-fu is correct, MyTardis templates using Author_Experiment.author to get an author's name will work unchanged if Author model's ```__unicode__``` method returns the author name (e.g. 'Firstname Lastname').

If we need to model the authors of a dataset independently of the authors of its parent experiment/s, this could be achieved via a many-to-many relationship between Author and Dataset through a new Author_Dataset model.

**Comment by millercathy** [comment]
@craigpatten Just a heads up - we plan to talk about this and #19 regarding how author names are captured/sent to DataCite with you on Tuesday 10/2 - Need to make a call on this Enhancement soon as #29 is also dependent on outcome.

**Comment by franksc** [comment]
Have moved discussion of author name handling to #38.

**Comment by franksc** [comment]
Work required to implement this:

- Implement new Author model + changes to MyTardis Author_Experiment and Experiment models
- Update MyTardis views/templates which retrieve author names from Author_Experiment table
- Update DOI minting (#19), citation display (#29) and any other functionality which needs to retrieve author names in inverted order
- Add 'add author' and 'edit author' forms to MyTardis frontend
- Update 'create experiment' and 'edit experiment' MyTardis frontend forms to support referencing records from Author table (this could require the most work)

**Comment by millercathy** [comment]
Rejecting in favour of #38
