### ISSUE TITLE
Extend DOI minting template to include additional metadata

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#19]
The [MyTardis template](https://github.com/mytardis/mytardis/blob/master/tardis/tardis_portal/templates/tardis_portal/doi/default.xml) used to generate an XML document using the DataCite metadata schema for passing to Cite My Data in minting a DOI implements only the DataCite mandatory elements title, creators, publisher and publication year.

[DataCite](http://dx.doi.org/10.5438/0010) (p. 5) recommends providing additional metadata, in particular the Description and ResourceType elements, to enhance and inform end user discovery and evaluation of resources for which DOIs are minted.

We could extend the MyTardis DOI template to include additional metadata where it exists in Experiment and other models, or can otherwise be determined. E.g:

MyTardis | DataCite
-------- | --------
Experiment.description|```<descriptions><description descriptionType="Abstract">[description]</description></descriptions>```
Type of resource: experiment or dataset|```<resourceType resourceTypeGeneral="[Collection|Dataset]" />```
Experiment.license.url, Experiment.license.name|```<rights rightsURI="[url]">[name]</rights>```
# of datasets, # of files in experiment|```<sizes><size>x datasets</size><size>y files</size></sizes>```

**Comment by Li-ReDBox** [comment]
I followed the link and found an XML example:http://schema.datacite.org/meta/kernel-3/example/datacite-example-full-v3.1.xml which has rights inside rightsList. Could @franksc or any one confirm which should I use? Thanks.

**Comment by Li-ReDBox** [comment]
Question:  if we use resourcetype, does that mean dataset's xml needs to be exteded too? If so, does dataset use fields in experiment if it does not have them? For example, description and license.

**Comment by franksc** [comment]
@Li-ReDBox see branch 'doi-template' for some preliminary work on this (NB not tested)

As this is flagged as only an enhancement request rather than a requirement, can we 'park it' temporarily while I write up a more detailed list of stuff to implement.

**Comment by franksc** [comment]
MyTardis records author names (in Author_Experiment table) as 'Firstname Lastname', but DataCite schema says creator names should be in form 'Lastname, Firstname'.

Commit modc08/mytardis@80c54f32e93bd508b5cb75888a5d6353fc03fdc4 implements inverting author names as recorded in MyTardis to the DataCite-preferred format in minting DOIs.

It will correctly handle John Smith, John Q. Smith and John Quincy Smith, but not John Smith Jr, John Smith III or Jon van der Smit. (The last word in the MyTardis author name needs to be the last name/surname.)

**Comment by Li-ReDBox** [comment]
Author is a free text field, the only existing rule is to have comma separting authors and urls.

**Comment by millercathy** [comment]
Thanks @franksc 
This is great... but I think we need to account for these multiple word surnames. This raises the importance of enhancement #18 
Can you check with Steve and/or Grischa how others are approaching before we discuss with @craigpatten about the feasibility of #18 ? Cc @Li-ReDBox

**Comment by franksc** [comment]
Have moved discussion of author name handling to #38.

**Comment by franksc** [comment]
modc08/mytardis@32094ab065d5f0dd79ec65108b58440e21510acd extends DOI minting (experiment and dataset) to include resource type, description, rights url/name and sizes
