### ISSUE TITLE
Experiments and datasets should be immutable once DOI minted

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#21]
Once a DOI is minted for an experiment or dataset it needs to be immutable – included data files or datasets can't be added or removed, and metadata that informs citation (title/name, creators, publication year etc) can't be modified.

The MyTardis Experiment and Dataset models have Boolean fields 'locked' and 'immutable' respectively (not sure why the names aren't consistent). However, some quick testing suggests this field being set to 'true' does not prevent an experiment or dataset's metadata being changed, or the datasets included in an experiment being changed; it does prevent files being added or removed from a dataset.

Requirements:
- When a DOI is minted for an experiment or dataset, the appropriate Boolean should be changed to 'true'
- When an experiment or dataset is set to immutable you can't add or remove included files or datasets, or modify metadata that informs citation

**Comment by Li-ReDBox** [comment]
Some changes have been made: https://github.com/modc08/mytardis/commit/8440e3bf2b1411f0ca547a28f4e7de54ac28675b
Currently, once owner of experiment or admin goes to admin interface, check the "Locked" checkbox, "Edit Experiment", "Sharing/Change public access" are disabled.

Another option is to update this property once an experiment has been minted.

The commited UI code might need more checks to ensure they are not redundant.

**Comment by franksc** [comment]
Testing:

When an experiment is set to public, and DOI minted:
- [ ] experiment is set to immutable/read-only – __doesn't happen__

When an experiment is set to immutable (I just did this manually via Django admin interface):
- [x] can't edit experiment metadata
- [ ] can't add datasets – __add datasets button not displayed so can't create and add new datasets, but can still select Transfer Datasets and drag in existing datasets from other experiments__

When a dataset has a DOI minted:
- [x] dataset is set to immutable

When a dataset is set to immutable:
- [x] can't edit dataset metadata (edit dataset button not displayed)
- [x] can't add files to dataset (add files button not displayed)

**Comment by franksc** [comment]
Testing 27 Jan from vm-develop-doi-20150127-092720:

- [x] when DOI minted, experiment is set to immutable/read-only
- [ ] when experiment locked, can still drag/drop datasets via Transfer Datasets – __still needs fixing__

**Comment by Li-ReDBox** [comment]
@franksc, I made changes to remove "Transfer Datasets" if experiment has previously published. During the process, if user does not reload page, "Transfer Datasets" will not disapper because page structure is kept and only ajax call to reload existing tabs. So when user clicks on that tab, updated state will be showing a message: You do not currently own any other experiments or this experiment is locked. This may not be the best solution but the most straight/simple way what I could think of. Please let me what you think.
 
commit: https://github.com/modc08/mytardis/commit/adfce6c7233c0eeb3143632d389a2bca4ecd9671

**Comment by franksc** [comment]
Sounds good to me @Li-ReDBox – have tested and this works as you described.
