### ISSUE TITLE
Batch ingest script functionality

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#22]
ACAD have okayed the idea of ingesting data into MyTardis by running a batch ingest script from the command line to slurp in data files from local storage and use the MyTardis REST API to create a new experiment/dataset hierarchy and populate with data files. (Usually they will be running from their RDSI machine as that's where their data files are stored, although it could be used to ingest straight from someone's local machine.)

I would suggest wettenhj's [mytardis-swift-uploader](https://github.com/wettenhj/mytardis-swift-uploader) could be used as a basis as it works using the MyTardis develop branch's storage box functionality, although it is set up to us Swift as an object store so this stuff may need to be rejigged/replaced. Alternatively there is Steve's earlier [mytardis-uploader](https://github.com/steveandroulakis/mytardis-uploader).

Here is a laundry list of required functionality:
- Option to specify the source directory from which to read data files, which will conform to this structure:
```
experiment/
	dataset1/
		file1
		file2
		subdirectory/
			file3
	dataset2/
		file4
		file5
```
- Option to delete files from local storage once successfully ingested into object store
- Options to specify the title, description and institution for the experiment to be created
- Option to specify datasets already in MyTardis to be linked to newly created experiment – for scenario in which new experiment/study incorporates some previously ingested data
- Option to do a 'dry run' and just echo what actions would be performed (e.g. listing what experiment and datasets would be created) without actually doing anything

Example usage: ```batchingest.py -f experiment -t "Title of experiment" -d "Description of experiment"```

**Comment by franksc** [comment]
To be implemented/changed:

- Remove option to set institution of experiment – we always want to use the default value (defined in MyTardis' settings.py)
- Option to delete files from local storage once successfully ingested into object store
- Option to set authors of experiment – I suspect this will require some extended handling on the MyTardis API side as author names are recorded in Author_Experiment rather than Experiment

**Comment by franksc** [comment]
ACAD have decided (during meeting on 6 Feb) that we do not require functionality to attach existing datasets to a newly created experiment through this batch ingest script – they are happy to do this through the existing MyTardis frontend functionality (Experiment - > Transfer Datasets -> drag'n'drop) as required.

**Comment by craigpatten** [comment]
@franksc excellent

**Comment by franksc** [comment]
Desired behaviour for ingesting metadata records: Before attempting to insert a new record found in Excel source file, look for a matching record (table+primary key combination) in the existing MyTardis data and if found skip inserting that record – *unless* when running ingest script user has passed an option (--force-update-metadata or something) to force inserting all records found in source file.

The idea here is that metadata records won't be updated/overwritten based from the Excel source file the user is provided, minimising the risk of data being unintentionally messed up, unless the user explicitly enables this behaviour.

**Comment by craigpatten** [comment]
Functionality exists as of modc08/mytardis@7080b90 and modc08/store@5920d09.

**Comment by craigpatten** [comment]
To-do list:
- [x] option for local file removal
- [x] handle authors
- [x] remove institution

**Comment by craigpatten** [comment]
Institution: modc08/store@f1f72cf

**Comment by craigpatten** [comment]
Author (server-side): modc08/mytardis@5f5b78b.

**Comment by craigpatten** [comment]
This code can handle the magic test spreadsheet of @franksc so I think we can call #22/#24 done. For any further problems, we can open specific issues.
