### ISSUE TITLE
Experiment model needs 'publication year' field

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#23]
Currently MyTardis just uses the current year as the value for DataCite element publicationYear in minting DOIs.

However, the DataCite schema indicates the value for publicationYear should be the 'year when the data was or will be made publicly available'. This may not be the current year at the time the DOI is being minted if an experiment is initially made publicly visible with metadata only, with the actual data files to be made available later.

Also, if we want to display a citation as part of the experiment and dataset views this needs to use the same publication year as was used in minting DOI for the resource.

We can handle both of the above by adding a 'publication year' (YYYY) field to the Experiment model. The default value can be the current year but it should be editable through the MyTardis front end before a DOI is minted. (Publication year is a property that can't be edited once a DOI is minted, cf. #21 .) Minting a DOI should use the value from this field for DataCite record's publicationYear, rather than the current year.

**Comment by Li-ReDBox** [comment]
Question: does __pulication year__ have any relationship with end_time?

**Comment by franksc** [comment]
@Li-ReDBox No – I think MyTardis' start_time, end_time, and created_time are meant to record dates/times when the actual experiment/research activity was conducted. (Although not sure how the end user is meant to set/edit these fields ...)

We want publication_year to be just a four-digit year (YYYY) to record when the data files associated with the experiment/datasets are being made publicly available – could be the current year if data is being made available right away, or 2016/2017/... if data is embargoed/not going to be publicly available until then.

So we need:
- a new publication_year field in experiment model, where the default value is the current year at time experiment object is created
- this field can edited via 'Edit Experiment' view
- DOI minting uses value of publication_year, rather than just current year at time DOI is being minted
- this field can't be edited once DOI is minted and experiment set to immutable

**Comment by Li-ReDBox** [comment]
publication_year added by https://github.com/modc08/mytardis/commit/bcb11d9efb3e16e246ce8284fa722bee35139925

**Comment by franksc** [comment]
Testing:

- [x] experiment field publication_year has default value of current year at time of object creation
- [x] field can be edited via 'Edit Experiment'
    - [x] can only edit to a four-digit year
- [ ] DOI minting uses value of publication_year – __appears implemented in modc08/mytardis@bcb11d9efb3e16e246ce8284fa722bee35139925 but need to verify__
- [x] can't edit field once DOI minted/set to immutable (yes because Edit Experiment view not available when experiment immutable)

**Comment by franksc** [comment]
Tested 30 Jan vm-develop-doi-20150130-155609:

- [x] DOI minting uses value of publication_year

Tested by tweaking ands_doi.py to log the XML it generates and sends to Cite My Data, setting an experiment's publication year to a future year, making experiment public to trigger DOI minting and examining the generated XML.
