### ISSUE TITLE
Ingest metadata from Excel source file

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#24]
We need a means to populate the models implemented in #2 with provenance and pipeline metadata relating to ingested datasets. ACAD have indicated their preferred option would be to load a source/template file such as a CSV or Excel doc containing this metadata.

An Excel document would seem preferable to a CSV as it allows for multiple sheets/tabs representing different metadata categories (Source, Sample etc) to be included in the one file. An Excel template file based on the MODC08 metadata schema has been prepared and ACAD have used it to provide some sample metadata.

Ideally this metadata ingest would be hooked into the data batch ingest workflow cf. #22, so when a metadata source file is encountered this would initiate a process to ingest the metadata it contains into the appropriate models/tables.

Example contents of a sheet for category Source:

Element name | Description | Value | ...some more columns...
---- | ---- | ---- | ----
id|Source accession id|Source1234|...
date|Date source was collected|1990-01-01|...
age_cat|Age category of source|adult|...

We are only interested in columns 'Element name' and 'Value', with values in the former matching the names of fields in the Source model.

It is quite possible a source file will have multiple sheets of the same type (e.g. Source1, Source2 or Source, Source1), so this will need to be handled.

**Comment by franksc** [comment]
We can take advantage of the (intentional) correlation between element names in the source Excel spreadsheet and field names in the Django models by extracting the element names and values into a Python dictionary (e.g. ```dict = {'id': 'Source1234', 'date': '1990-01-01', 'age_cat': 'adult'}```) and passing this dictionary as keyword arguments when creating a new Django object of the corresponding model.

For this to work we would need to append '_id' to any element names in the spreadsheet where they correspond to fields which are foreign keys to another model/table. E.g. if in Source model we have a field 'organism' as a fk to Organism model, in the spreadsheet this would need to be 'organism_id'.

**Comment by franksc** [comment]
Commit 283ef25b2d546739f5d1a4314c6111b51f0429e9: Have reworked this to read data from Excel source and return a JSON representation suitable for passing to Django's serializers.deserialize(), rather creating new objects directly.

Using this method the '_id' trick described above for setting foreign keys is not necessary.

**Comment by franksc** [comment]
The state of play:

- We have (cf. #2) models/tables for ACAD provenance and pipeline metadata records (Source, Sample, Extract etc), integrated into MyTardis and ready to receive data.

- We have an Excel template that ACAD will be using to record metadata associated with their datasets, with multiple sheets/tabs containing different record types (Source, Sample etc).

    - There is no fixed set or pattern to what metadata record types will appear in the file, e.g. a Source relating to the dataset could be included, or equally no Source could appear if it has already been loaded as part of a previously uploaded dataset. The only assumption is that each dataset's ACAD-model metadata will include exactly one Analysis record, which has a one-one relationship with a MyTardis dataset.

- We need functionality for ACAD to drop an Excel template file into each dataset-to-be-uploaded directory and have this metadata be read from the Excel file and loaded into the appropriate ACAD models/tables in MyTardis as part of the batch ingest process (cf. #22). This includes recording the relationship between the dataset's Analysis metadata record and the MyTardis dataset created as part of the ingest process.

- 283ef25b2d546739f5d1a4314c6111b51f0429e9 implements reading each sheet in the Excel template file and returning a JSON representation suitable for passing to Django's serializers.deserialize() – this should take care of loading ACAD-model metadata into the appropriate tables.

**Comment by franksc** [comment]
A possible solution:

- When globbing files within a dataset directory to upload to MyTardis, ingest script to look for (say) Excel file metadata.xlsx and use ReadFromExcel class to extract ACAD-model metadata in JSON format (NB we don't need to upload this file)

- POST this ACAD-model metadata along with MyTardis id of recently created new dataset to a new MyTardis API endpoint e.g. /api/v1/acadmetadata/:
```json
{
    "dataset": "99",
    "acad_metadata":
        [
            {
                "model": "acad.source",
                "pk": "Test123",
                "fields": {
                    "age_range": "25-30",
                    "other_fields": "also go here"
                }
            }
        ]
}
```
- API endpoint for /acadmetadata/ to grab JSON blob from acad_metadata and pass it to Django's serializers.deserialize() for populating ACAD metadata tables. Where it notices it's creating an object of class 'Analysis', insert the id of the recently created dataset into this object's 'dataset' field as a fk to tardis_portal.Dataset:
```python
for obj in serializers.deserialize('json', acad_metadata):
    if obj.object.__class__.__name__ == 'Analysis': # no comments on this hackery please ...
        obj.object.dataset = dataset_id
    obj.save()
```
(Not sure this is going to win any RESTful points ...)

**Comment by franksc** [comment]
modc08/modc08@d51b04e348b25a3155a03414812a809d7fabfee8 Update ReadFromExcel class to use new template format

**Comment by craigpatten** [comment]
Updates at https://github.com/modc08/modc08/issues/22#issuecomment-75774589.

**Comment by craigpatten** [comment]
This code can handle the magic test spreadsheet of @franksc so I think we can call #22/#24 done. For any further problems, we can open specific issues.
