### ISSUE TITLE
Open VCF, BAM files in external genome browser

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#25]
Discussion with an SA medical researcher has highlighted the desirability of the ability to open VCF or BAM files in an external web-based genome browser.

The popular [UCSC Genome Browser](http://genome.ucsc.edu/) (there is an [Aus mirror](https://ucsc.genome.edu.au/)) allows for externally hosted data files to opened using a URL like ```http://genome.ucsc.edu/cgi-bin/hgTracks?org=human&position=chr22&
hgt.customText=http://genome.ucsc.edu/goldenPath/help/test.bed```. There is also the option to list the URLs and properties of multiple 'tracks' (data files) in [one text file](http://genome.ucsc.edu/goldenPath/help/customTrack.html#TRACK) and point the genome browser at that to open all the files as a batch – we could maybe have one of these track files per dataset.

However, I tried with a VCF file stashed in a test MyTardis and found the MyTardis ```/datafile/view/nnn``` URL to retrieve a file only works within a browser session (I guess this is a security thing to prevent non-authenticated users getting non-public files) – trying it somewhere else returns a 403: http://genome.ucsc.edu/cgi-bin/hgTracks?org=human&position=chr22&hgt.customText=http://203.101.225.113/datafile/view/5/

@craigpatten Is there a way we can get URLs that allow given data files to be retrieved directly via the object store?

**Comment by millercathy** [comment]
Confirming that @craigpatten agreed we can get URLs in our meeting on Friday 30/1 - we need to nominate a time for these to remain valid so that they can be viewed in an external browser. What is the default?
@Li-ReDBox will assign this over to you but conscious that we need to get a bit more info to you. In the meantime can you explore?

**Comment by franksc** [comment]
@Li-ReDBox Some stuff to get this started:

In the MyTardis dataset view, for any file with extension .vcf or .bam* we want a link 'Open in genome browser' which opens in a new window a URL with form ```http://genome.ucsc.edu/cgi-bin/hgTracks?org=human&hgt.customText=url``` where ```url``` is a direct URL to the file on the object store. This URL needs to be persistent/not expire as end users could want to keep one of our data files open in the external genome browser for some time.

(* We should probably do this by mime type, but extension will do for now ...)

The main thing here is to get the external genome browser successfully reading and displaying one of our data files; once that is working we can start adding in various parameters supported by the browser's (rather strange) URL syntax.

**Comment by Li-ReDBox** [comment]
Initial work has been [committed](https://github.com/modc08/mytardis/commit/a6de24dc94efafe06a1bed4950891b0ea8647a62). Right now, `get_s3_url()` returns a static string which can be used to open genome browser. Once we have API to the object store, this can be updated.
Please suggest a better icon to the link of opening the browser.
Please advice if there is any misunderstanding.

**Comment by franksc** [comment]
@craigpatten If files on the object store are being streamed through MyTardis rather accessed directly via object store (cf. #39), does this mean Datafile model's get_download_url() method is the way of getting a download URL for the object?

**Comment by franksc** [comment]
I tested using get_download_url() (in place of get_s3_url() ) and it worked okay in loading an example VCF data file into the genome.ucsc.edu browser.

**Comment by franksc** [comment]
modc08/mytardis@fcce7e8d1fa083fd7680f8aec4ad15326891e19e switches this to use get_download_url() rather than get_s3_url(), plus makes some other tweaks. (plus URL bugfix modc08/mytardis@c5cee1f5dc8509535192b80026921d149135a1d3)

**Comment by millercathy** [comment]
@franksc Hi Chris, do we have sufficient feedback from ACAD to close this?

**Comment by franksc** [comment]
Closing as does what is required i.e. click a button in MyTardis and it reads/opens data file in UCSC genome browser.

Have raised with ACAD the current behaviour of passing parameter `org=human` ('latest human reference genome') to UCSC browser vs explicitly specifying via `db=xxx` the reference genome (e.g. hg19) to which the data file was aligned.
