### ISSUE TITLE
Publication identifiers display linked via appropriate resolution service

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#26]
A number of fields in the MODC08 metadata schema will contain publication identifiers such as a DOI or PubMed ID to refer to a research article or other publication -- or alternatively a full HTTP URL.

These should display in the frontend linked to the publication via appropriate resolution service, or just an active link if a full HTTP URL:

Publication ID | URL
----|----
doi:10.1234/5678 | http://dx.doi.org/10.1234/5678
hdl:1234/5678 | http://hdl.handle.net/1234/5678
pmid:12345678 | http://www.ncbi.nlm.nih.gov/pubmed/12345678

**Comment by millercathy** [comment]
@franksc are these fields defined in the pipeline metadata? Or Experiment metadata?

**Comment by franksc** [comment]
Pipeline metadata, in fields Extract.protocol_ref and Library.protocol_ref .

If we need to linkify publication ids that appear as part of a larger block of text, such as an experiment's description field, this will require more advanced handling than in example implementation modc08/mytardis@af558d7fce933bd6332216b9ca1f2cd49d5f2b56 which just defines a Django filter you can wrap around text you know will contain a pubid .

**Comment by millercathy** [comment]
Hi @Li-ReDBox So these two fields mentioned in @franksc 's comment above are the ones that contain links which need to be resolvable.

**Comment by Li-ReDBox** [comment]
Is this the real link of above mentioned, @franksc? https://github.com/modc08/modc08/commit/af558d7fce933bd6332216b9ca1f2cd49d5f2b56. The above one returns 404.

**Comment by Li-ReDBox** [comment]
Just a reminder to myself: will finish this task when Pipeline metadata has been worked, so DOI and other handlers will be dealt at the same time.

**Comment by franksc** [comment]
Ooops; fixed.

**Comment by millercathy** [comment]
Like

**Comment by franksc** [comment]
Sample implementation works in MyTardis for test cases described above
