### ISSUE TITLE
Update MyTardis licence fixtures

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#28]
Once a decision is made on what licence option/s (there may only be one) will be available for MODC08 data, need to update the ['out of the box' MyTardis licence fixtures](https://github.com/modc08/mytardis/blob/modc08/tardis/tardis_portal/fixtures/cc_licenses.json).

**Comment by millercathy** [comment]
@franksc We can make a call on this now, yes?

**Comment by franksc** [comment]
In MyTardis branch 'licences' have:
- edited Creative Commons licence fixtures to use only CC BY 4.0 (modc08/mytardis@533df8eb4c0f62c22a3273040aa60bc3168628ab)
- removed the licence legal text display (this was just displaying 'lorem ipsum' placeholder text – presumably not fully implemented by MyTardis devs) and tweaked wording of licence info block to indicate both experiment data and metadata is being licensed (modc08/mytardis@f34deb29e83c1535d29cf942e61183fa4c1bf4b9).
