### ISSUE TITLE
Display citation block in experiment and dataset views

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#29]
Experiment and dataset views should display a citation block following this format:

Creator1; Creator2 (PublicationYear): Title. Publisher. ResourceType. Identifier

e.g.
Llamas, Bastian; Haak, Wolfgang (2014): _Awesome ancient human DNA experiment_. Australian Centre for Ancient DNA, University of Adelaide. Collection. http://dx.doi.org/10.5072/1234

MyTardis wants author names stored as 'Firstname Lastname' but in a citation they need to display as 'Lastname, Firstname'. (maybe apply some regular expression magic)

For an experiment ex:
- PublicationYear = ex.publication_year (cf. #23)
- Title = ex.title
- Publisher = ex.institution
- ResourceType = 'Collection'
- Identifier = DOI of experiment

For a dataset ds with chronologically earliest parent experiment ex:
- PublicationYear = ex.publication_year
- Title = ds.description
- Publisher = ex.institution
- ResourceType = 'Dataset'
- Identifier = DOI of dataset

**Comment by millercathy** [comment]
Hey @Li-ReDBox 
Can a citation appear on each experiment and dataset as outlined above? This isn't shown in the mockups attached to #5. It can appear as 'Please cite this resources as: citation'.
Please note that @franksc is working on reversing name order in #19

**Comment by Li-ReDBox** [comment]
I am not sure if I have missed anything which happend a bit, I did not find citation section in mock-up in #5. But I will start working on backend code now.

**Comment by millercathy** [comment]
Hi @Li-ReDBox - no you haven't missed anything! The citation section is NOT shown in the mock-up. We overlooked it when those mock-ups were produced.
Thanks

**Comment by Li-ReDBox** [comment]
Hi, I need clarification of dataset's _chronologically earliest parent experiment ex_. Is this referring to *Start time* or *Publication year*?
Thanks

**Comment by millercathy** [comment]
Hi @Li-ReDBox that refers to the first experiment that the dataset is included in. Because datasets can belong to multiple experiments, they will only get one DOI and one citation when they are first minted with the first experiment. The dataset adopts the publication year from the experiment metadata the first time it is published. Thereafter the DOI and citation information will not change. Does that answer your question?

**Comment by Li-ReDBox** [comment]
If that is the case, it should be fine. I just checked, it is the method used to find out which parent experiment is to use when a dataset is minted. Which is good.

Could it be possible that, a dataset has been attached to multiple experiments, and user decides to mint an experiment which is not the earliset created one? If this is the case, minting code has to be changed and this relationship has to be saved. What do you think?

**Comment by millercathy** [comment]
It is possible that an experiment is created but not published and a subsequent experiment containing a duplicate dataset is minted in the interim... @franksc This shouldn't present a problem, should it? Because the DOI metadata is created at point of minting? Can @franksc confirm? Thanks!

**Comment by Li-ReDBox** [comment]
Q: should author_url be included?

**Comment by millercathy** [comment]
@Li-ReDBox No
@franksc What's our source for citation format?

**Comment by franksc** [comment]
[DataCite metadata schema v3.1](http://dx.doi.org/10.5438/0010), p. 7 'Citation'. Although this is just DataCite's recommended format, so we don't necessarily have to follow it exactly ...

**Comment by franksc** [comment]
Have moved discussion of author name handling to #38.

**Comment by Li-ReDBox** [comment]
Add initial template for display citation: https://github.com/modc08/mytardis/commit/0dfc198bb2c1d96234cbf5d29058e9ab7f7b03fc.

This templaet needs to be tidied up: e.g. removing reminders, heading, etc.

**Comment by franksc** [comment]
Li raises an excellent point that it is fudgy for a dataset to determine its 'direct parent' experiment, from which it should derive some metadata like authors and publication year, based on looking up the chronologically earliest of its set of parent experiments.

Have reopened #12 to remove this fudginess and improve DOI minting for datasets, including recording in Dataset model its 'direct parent' experiment – @Li-ReDBox this should be used in displaying citation rather than using chronologically earliest parent as described above.

**Comment by franksc** [comment]
@Li-ReDBox Three tiny tweaks:
- Italicise the 'Title' component
- Make the http://dx.doi.org/... URL component a live hyperlink to that URL
- Add a 'hanging indent' to the citation block so lines after the first line display indented by, say, 3em

**Comment by Li-ReDBox** [comment]
Used a wrong link, so the commit does not show up here. The commit is on [develop-doi branch](https://github.com/modc08/mytardis/commit/746aff4ea6155298f77cf839ac506c0044b61514)

**Comment by franksc** [comment]
:+1:
