### ISSUE TITLE
Add delete experiment/dataset/file functionality

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#30]
Discussion with ACAD has confirmed we need functionality to delete experiments, datasets and files via the MyTardis web frontend, rather than dropping into the Django admin backend.

We want:

- In Experiment view, a button 'Delete Experiment' which deletes the experiment
    - Should not display if experiment is set to immutable
- In Dataset view, a button 'Delete Dataset' which deletes the dataset
    - Should not display if dataset is set to immutable
    - Separate to the 'X' which shows in dataset sidebar of experiment view, allowing you to unlink dataset from the experiment (doesn't delete dataset)
- In Dataset view in the files sidebar, a button next to each file which deletes the file
    - Should not display if parent dataaset is set to immutable

These delete buttons should display an 'are you sure?' confirmation popup, if practical.

Deleting an experiment should also attempt to delete all child datasets. Attempting to delete a dataset should fail if the dataset is attached to more than one experiment.

Deleting a dataset should also delete all files included in the dataset.

**Comment by franksc** [comment]
Ideally 'deleting a file' will both delete representations of the file in MyTardis and, if it can be determined the only/last remaining representation of the file was just deleted, also interact with the storage layer to delete the file/object there too. (Otherwise a file could be totally removed from MyTardis yet remain sitting on the storage taking up space.)

@craigpatten

**Comment by millercathy** [comment]
Hi @Li-ReDBox can you treat this task as a priority when you get to the project work on Thursday, please?
We are aiming to resolve all milestone phase 2 tasks by end of week. Thank you.

**Comment by Li-ReDBox** [comment]
no problems

**Comment by Li-ReDBox** [comment]
@franksc, in the request, it says:
_Separate to the 'X' which shows in dataset sidebar of experiment view, allowing you to unlink dataset from the experiment (doesn't delete dataset)_
I cannot find "X" on dataset sidebar. Do you have a screen shot? What am I missing?
Thanks

**Comment by franksc** [comment]
![screen shot 2015-02-12 at 15 51 04](https://cloud.githubusercontent.com/assets/8837821/6162216/28fd2e98-b2cf-11e4-985a-82a001ad4202.png)

**Comment by Li-ReDBox** [comment]
@franksc that is very clear and helpful. Many thanks

**Comment by Li-ReDBox** [comment]
First round of deletion has been done. Need more tests. https://github.com/modc08/mytardis/tree/del_assets

**Comment by Li-ReDBox** [comment]
Also, files are left behind in storage

**Comment by franksc** [comment]
Testing:

- In Experiment view, a button 'Delete Experiment' which deletes the experiment :white_check_mark: 
    - Should not display if experiment is set to immutable :white_check_mark: 
- In Dataset view, a button 'Delete Dataset' which deletes the dataset :white_check_mark: 
    - Should not display if dataset is set to immutable :white_check_mark: 
- In Dataset view in the files sidebar, a button next to each file which deletes the file :white_check_mark: 
    - Should not display if parent dataaset is set to immutable :white_check_mark: 
- These delete buttons should display an 'are you sure?' confirmation popup :white_check_mark: 
- Deleting an experiment should also attempt to delete all child datasets :white_check_mark: 
- Attempting to delete a dataset should fail if the dataset is attached to more than one experiment
    - **Not implemented quite as described** – if a dataset is attached to more than one experiment then the Delete Dataset button isn't displayed, which does prevent the dataset being deleted but this is not the behaviour we want. For the sake of UI consistency the delete button should be displayed but action to delete the dataset should fail with an error message (see comments below)
- Deleting a dataset should also delete all files included in the dataset :white_check_mark: 

Top work Li.

@Li-ReDBox To enforce the logic of when resources can and can't be deleted, can you please add the following:

- Action to delete an experiment should fail if the experiment is set to immutable
- Action to delete a dataset should fail if dataset is set to immutable
- Action to delete a dataset should fail if dataset is attached to more than one experiment
- If action to delete a resource fails, an error popup should be displayed ('Can't delete: [reason]')

(This is to avoid incorrect behaviour in unlikely but possible scenarios such as an experiment being set to immutable (e.g. it was published/DOI minted) but a user already has the experiment view open with the 'Delete Experiment' button displayed – clicking the button at this point will successfully delete the experiment, even though it's immutable/shouldn't be deletable.)

**Comment by franksc** [comment]
@Li-ReDBox can you please liaise with @craigpatten if necessary to implement:
- Deleting a file will both delete representations of the file in MyTardis and, if it can be determined the only/last remaining representation of the file was just deleted, also interact with the storage layer to delete the file/object there too

**Comment by Li-ReDBox** [comment]
@franksc, thanks for testing. Two commits:
https://github.com/modc08/mytardis/commit/fc61bef8b91ccad5f127330105a96b589aa1a845: Action to delete an immutable resource raise an exception
https://github.com/modc08/mytardis/commit/3a1e2c547316c4d583487a2e37575d3fddd4a3ab: Change display to include 'Can't delete

**Comment by Li-ReDBox** [comment]
In terms of delete file from storage, I don't have much understanding of storage backend.

Also I am not sure if storage has been touched by mytardis' default action compared to save: https://github.com/mytardis/mytardis/blob/develop/tardis/tardis_portal/models/datafile.py#L352
delete: https://github.com/mytardis/mytardis/blob/develop/tardis/tardis_portal/models/datafile.py#L364

Please correct me if I am wrong

**Comment by craigpatten** [comment]
Deletion of data from the storage backend can/should be an asynchronous garbage collection which can be done lazily, i.e. it doesn't need to be done at the precise time of metadata deletion.

**Comment by franksc** [comment]
Sounds good @craigpatten – split into new issue #43

**Comment by franksc** [comment]
More testing:

- Action to delete an experiment should fail if the experiment is set to immutable :white_check_mark: 
- Action to delete a dataset should fail if dataset is set to immutable :white_check_mark: 
- Action to delete a dataset should fail if dataset is attached to more than one experiment :white_check_mark: 
- If action to delete a resource fails, an error popup should be displayed ('Can't delete: [reason]') :white_check_mark:

**Comment by franksc** [comment]
modc08/mytardis@b1b7aa2efa66541a647b983ac8adbc3960275f64 tweaks UI so Delete Dataset button is always displayed for non-immutable datasets, even if dataset can't be deleted due to attachment to another experiment (or experiments).

Also, have confirmed that if user attempts to delete an experiment containing a shared dataset, this will fail with error popup that 'Dataset [name] is attached to more than one experiment'
