### ISSUE TITLE
Taking an authorless experiment public fails with unhelpful error

### ISSUE THREAD

**Issue by craigpatten** [modc08/modc08#32]
I realised why some DOI mintings would fail with an internal server error &mdash; it is because an empty author field will lead to a schema validation error. For example:

```
[29/Jan/2015 23:18:16] ERROR 127.0.0.1 modc08 POST /ajax/experiment/8/rights unrecognised response: {
  "response": {
    "app_id": "...",
    "doi": null,
    "message": "The metadata you have provided to mint a new DOI has failed the schema validation.Metadata is validated against the latest version of the DataCite Metadata Schema.For information about the schema and the latest version supported,please visit the ANDS website http://ands.org.au.Detailed information about the validation errors can be found below.",
    "responsecode": "MT006",
    "type": "failure",
    "url": "http://demo.modc08.ersa.edu.au/experiment/view/8/",
    "verbosemessage": "Document Validation Error: Line 4: Element '{http://datacite.org/schema/kernel-2.1}creators': Missing child element(s). Expected is ( {http://datacite.org/schema/kernel-2.1}creator ).\n"
  }
} 500
```

Perhaps it would be nice to disable minting unless the required fields are present?

cc @millercathy @franksc

**Comment by millercathy** [comment]
@craigpatten Thanks, Craig. Yes! Can we absolutely disable minting unless minimum metadata is present. Cc @franksc

**Comment by Li-ReDBox** [comment]
Author has a foreign key points to experiment and this relationship is reenforced through UI. When you create/edit an experiment on the web form, without author, you can not save it. I reckon this issue happens when experiment is created in batch mode in which case, author which should be a required field missed, aka, schema is not enforced.

**Comment by franksc** [comment]
Functionality in #22 to set authors in association with an experiment when creating via API/command line, if it can be achieved, should avoid the situation of experiments being created without any authors.

However, for the sake of completeness we should probably perform some basic validation of the metadata used to populate the DataCite template before attempting to mint a DOI (via supplying said populated template to Cite My Data).

@Li-ReDBox I would suggest doing this in ExperimentDOIService._datacite_xml(): raise some exception if ex.title, ex.institution_name, or ex.publication_year aren't set, or length of list of author names is zero

**Comment by millercathy** [comment]
Hi @craigpatten should this be assigned to you? I know we talked about it...?

**Comment by franksc** [comment]
N/A as should never be possible to create an authorless experiment, or an experiment which doesn't have all metadata required for minting DOI.
