### ISSUE TITLE
Extend search to all metadata

### ISSUE THREAD

**Issue by millercathy** [modc08/modc08#33]
This task is dependent on decision and implementation arising from #6 
The search functionality should be extend to incorporate searching across all pipeline metadata, i.e. Experiment metadata and fields in the Source, Sample, Extract, Library, Sequence, Processing and Analysis tables.

**Comment by shundezhang** [comment]
@millercathy would you prefer google-like search (one single search box to search everything) or form-based search (like what synchrotron has)?

**Comment by millercathy** [comment]
Both. See also #35 
Thanks! @shundezhang

**Comment by franksc** [comment]
Some points of clarification:

1. The metadata schema contains some fields defined as not for public display/consumption, which we don't want indexed

2. We may not want the contents of every single (public) model field to be used to populate the document/full text index – as suggested by the [Haystack 'Best Practices' guide](http://django-haystack.readthedocs.org/en/latest/best_practices.html#well-constructed-templates), we should use the fields that 'provide good content or include terms you think your users may frequently search on'
    - Random example: we may not want to index the values of Source.carbondate_years as it's unlikely an end user will want to enter some arbitrary number and retrieve results for sources matching that exact number of carbon date years

3. Additional search fields should be defined where we want to support limiting/filtering results based on the contents of certain model fields. For example, any metadata schema field for which we want a dropdown in the advanced search form/builder implies a corresponding search field.

In previous discussions ACAD have suggested end users are more likely to be searching for metadata at the Source/Sample end of the pipeline, so we might expect fields from these models to be more heavily represented for both 2 and 3 above.

Brainstorming likely end user search scenarios and example queries will probably assist in determining which metadata/model fields to include and exclude.

**Comment by franksc** [comment]
@shundezhang For the MyTardis Experiment model here is a breakdown of what fields should be in the document index and/or be indexed in a separate search field (executive summary: just title, description and publication_year)

Field|Document index|Search field|Comments
----|----|----|----
url | N | N | Field not in use by us
approved | N | N | Field not in use by us
title | Y | Y |
institution_name | N | N | Value for this field will always be 'Australian Centre for Ancient DNA'
description | Y | Y |
start_time | N | N | Field not in use by us
end_time | N | N | Field not in use by us 
created_time | N | N | Field not in use by us
update_time | N | N | Field not in use by us
created_by | N | N | Not meaningful for search
handle | N | N | Field not in use by us
locked | N | N | Not meaningful for search
publication_year | Y | Y |
public_access | N | N | Not meaningful for search
license | N | N | Not meaningful for search

We will also want to index the author names associated with each experiment in Author_Experiment table, in both the document index (so query for 'Wolfgang Haak' retrieves experiments of which Wolfgang is an author) and a separate search field ```experiment_author``` (so ```experiment_author:Haak NOT Llamas``` retrieves Wolfgang's experiments except where Bastien Llamas is also an author)

**Comment by shundezhang** [comment]
@franksc the syntax should be experiment_author:(Haak NOT Llamas). It must have the brackets otherwise won't work. For more details please see http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-string-syntax

**Comment by shundezhang** [comment]
@franksc this is done. Actually it doesn't hurt to have more fields indexed. Only the document index needs to be limited to the fields we care about.

**Comment by franksc** [comment]
Have provided @shundezhang with a copy of MODC08 metadata schema with annotations on where fields should be indexed in document/full text index and standalone search fields should be created

**Comment by franksc** [comment]
I believe this is done with modc08/mytardis@888aa3ba3443e666276b465fd2bc021dbbe3524c

**Comment by franksc** [comment]
Can we now please include Experiment.institution_name in the document index and as a standalone search field – there now could be a range of values in this model field (rather than just 'Australian Centre for Ancient DNA')

Also it would appear author names are not being included in the document index – on vm-frontend-20150226-145119 there is an experiment with author John Doe, but a query for "john doe" returns no results whereas experiment_author:"john doe" does.

**Comment by shundezhang** [comment]
I'll add Experiment.institution_name to the search index and author names in the document index.

**Comment by shundezhang** [comment]
fixed in the above commit.

**Comment by franksc** [comment]
:+1:
