### ISSUE TITLE
Add basic keyword search box

### ISSUE THREAD

**Issue by millercathy** [modc08/modc08#34]
This task is dependent on decision and implementation of #6 and also #33.
Search functionality should be extended to allow searching across all metadata and a basic keyword search box should be added to the search form.

**Comment by franksc** [comment]
In addition to simple keyword querying it is desirable for the single search box to support phrase querying, field-based querying, wildcarding, Booleans etc as provided by the search backend and its query syntax (e.g. the Lucene query syntax if we end up using a Lucene-based backend)

This will satisfy 'power users' with complex search requirements and/or a preference for directly entering their queries, and perhaps reduce the need for the advanced search form (#34) to accommodate uncommon search scenarios.

@shundezhang Based on some testing from the current modc08/mytardis 'search' branch, using Lucene syntax in the single search box, this should be achievable?

**Comment by franksc** [comment]
Have confirmed with @shundezhang that the currently implemented single search box, as an interface to querying the Elasticsearch backend, supports the full [Lucene query syntax](http://lucene.apache.org/core/2_9_4/queryparsersyntax.html) including field searching, wildcarding, range querying, and Boolean operators plus grouping of parameters (i.e. ```Africa AND (skull OR tooth)```)

:+1:
