### ISSUE TITLE
Customise advanced search

### ISSUE THREAD

**Issue by millercathy** [modc08/modc08#35]
Customise advanced search form and search functionality to encompass drop down search options for specific fields with defined terms.
@franksc to identify which fields these are (from metadata schema).

**Comment by millercathy** [comment]
This tasks is dependent on #6

**Comment by franksc** [comment]
Fields taking a fixed set of options:
 - Source.gender, Source.age_cat, Source.geoloc_continent
 - Sample.sample_cat, Sample.env_package
 - Library.source, Library.layout, Library.type, Library.enrich_method, Library.enrich_target,

**Comment by franksc** [comment]
ACAD have indicated in previous discussions that they expect the majority of end users will want to search at the source/sample end of the pipeline. I think there is a need for an advanced search form/builder to support queries/query parameters such as:

- Continent = Africa (pick from a dropdown list of options for Source.geoloc_continent. This should support selecting one or more options)
- Organism = Homo sapiens OR Denosivan (again, dropdown list should support selecting one or more options)
- Gender = male
- Age category = adult
- Carbon date age: range between x and y years (some kind of slider widget would be good here e.g. [this jQuery one](https://jqueryui.com/resources/demos/slider/range.html))

**Comment by millercathy** [comment]
Hello, sorry for initial confusion.
@franksc can you please itemise below the fields with fixed set options for which we require a drop-down menu in the advanced search.
Thanks

**Comment by franksc** [comment]
In addition to the global 'single search' box in the MyTardis header, which allows for simple keyword searching plus advanced searching using the Lucene syntax, we need a standalone page providing advanced search functionality.

This page should have (from top to bottom):
- Another single search/text entry box for entering keyword-based queries
- Below this we will put some help text (to be supplied) with example keyword queries 
- An advanced search builder with:
  - Dropdown for gender (Source.gender)
  - Dropdown for age category (Source.age_cat)
  - Set of checkboxes for options from Source.geoloc_continent (Africa, Antarctica, Asia, Australia, Europe, North America, South America). User can check one, many or zero options.
    - If user checks Africa and Asia, resulting query is `source.geoloc_continent:(Africa OR Asia)`
  - A slider widget (cf. #41), if practical, for carbon date range query (Source.carbondate_years); failing that, two text entry boxes for 'For' and 'To' values.
    - Desired query here is something like `source.carbondate_years:[1500 TO 2500]`
- At the bottom, button 'Search' to execute the query and button 'Reset' to reset everything back to default state

(It is anticipated this initial selection of dropdowns/widgets will be refined based on feedback from ACAD.)

The text query box and the advanced search widgets should be linked so user can combine both in constructing their desired query. E.g. if user enters some keywords in the text box and picks 'male' from the Gender dropdown, resulting query should be `source_gender:male AND "keywords they entered"`

**Comment by franksc** [comment]
Diagram:

![scan 14 feb 2015 12_50-page1](https://cloud.githubusercontent.com/assets/8837821/6405249/214e93fa-be71-11e4-9e9f-ffb6162b9dba.jpg)

**Comment by franksc** [comment]
Closing this as looks and works as expected per above – can reopen if we want to add more dropdowns and other widgets or make other changes
