### ISSUE TITLE
Author name handling (Firstname Lastname vs Lastname, Firstname)

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#38]
MyTardis records the names of authors in association with experiments in Author_Experiment.author . Author names are entered in direct order (Firstname Lastname) as comma-separated list ('Cathy Miller, Craig Patten, Jianfeng Li') when creating/editing an experiment, which is split at the commas to create entries in the Author_Experiment table for each author name in direct order.

We want author names to display in direct order in the experiment view, but in minting DOIs (#19) and displaying citations (#29) they should be in inverted form Lastname, Firstname (or Lastnames, Firstnames).

modc08/mytardis@80c54f3 attempts to handle this for minting DOIs by applying a regular expression to take Lastname and append ', ' then Firstname/the words preceding Lastname. This correctly handles some cases but not others:

Direct|Inverted
-----|----
John Smith | Smith, John
John Q. Smith | Smith, John Q.
John Quincy Smith | Smith, John Quincy
John Smith Jr. | Jr., John Smith :x:
John Smith IV | IV, John Smith :x:
Johan van der Smit | Smit, Johan van der :x:
[Juan Carlos Ferrero Donat](http://en.wikipedia.org/wiki/Juan_Carlos_Ferrero) | Donat, Juan Carlos Ferrero :x:

It is difficult to programmatically handle all national/regional naming conventions or cases which require knowledge about a particular individual e.g. in a Spanish name with multiple given names and two surnames, which is the first surname that should come first in the inverted name form?

A possible solution:
- an optional inverted_name field which allows for the correct inverted form of an author name to be manually entered
- a get_inverted_name() method that returns the inverted form of an author's name – use the value of inverted_name if set, otherwise apply regular expression/some other string processing approach to generate

As discussed in #18 it is a less than optimal design to record author name/info directly as part of the set of authors associated with an experiment, rather than modelling authors as standalone entities. If a particular author needs their inverted_name to be manually entered, this would need to be set for every entry they have in Author_Experiment table.

**Comment by millercathy** [comment]
After discussion this morning with @craigpatten agreed solution is as follows:
Change entry of name to MyTardis to inverted form i.e. Last Name, First Name.
Currently multiple authors are comma separated. Suggest alternative delimiters are used to indicate inversion of name AND separated authors. For example:
Miller, Cathy; Franks, Christopher; van den Berg, John
Last Name, First Name should therefore be in correct format for DOI minting and citation metadata.
@Li-ReDBox can you please work on this before Milestone/Phase 4 tasks? Many thanks!

**Comment by Li-ReDBox** [comment]
In Chris' email: 
3. Improving the modelling of experiment authors in MyTardis (see modc08 closed issue #18) is going to be looked at after the 3.6 release.
Does it have any impact on this issue?
Thanks

**Comment by franksc** [comment]
@Li-ReDBox No – this is just in the future/on the horizon for MyTardis core (no firm date on when it's going to happen), so we should just proceed with implementing what is described above

**Comment by Li-ReDBox** [comment]
@franksc, thanks I will work on this as the next task.

**Comment by Li-ReDBox** [comment]
Quick update:
https://github.com/modc08/mytardis/commit/6127ca094ae2f6e7a8370b62d70155d076dab006: Add a choice to the form to allow user to type in authors in the form of n,n;n,n
https://github.com/modc08/mytardis/commit/80c54f3: add a function to inverte names. Not used by any yet.
These are preliminary work, please make suggestions and corrections.

**Comment by Li-ReDBox** [comment]
The latest code is here: https://github.com/modc08/mytardis/commit/281ccfae91c4b7f19a167b1ffcb9d943f2a89c38

During the course, I wrongly pushed two commits into del_assets branch: 6127ca0 and 3a1e2c54. These two have been picked into develop-doi branch now. Not sure if there will be some confusion when merge into main branch.

**Comment by franksc** [comment]
@Li-ReDBox Testing from modc08/mytardis@281ccfa shows author name handling is not functioning as expected.

1. Create a test experiment and in Authors field enter 'Lastname, Firstname; Lastname2, Firstname2'
2. We would expect this string to be split at the ';' separator and two entries be created in Author_Experiment table for 'Lastname, Firstname' and 'Lastname2, Firstname2'
3. However, we get *three* entries in Author_Experiment: 'Lastname', 'Firstname; Lastname2' and 'Firstname2'

**Comment by Li-ReDBox** [comment]
Bug has been confirmed. The setting was missed.

**Comment by franksc** [comment]
Testing:

1. Create a test experiment and in Authors field enter 'Lastname, Firstname; Lastname2, Firstname2'
2. In Author_Experiment table we should get two entries 'Lastname, Firstname' and 'Lastname2, Firstname2' :white_check_mark: 

However, in Experiment view author names are displaying as 'Firstname**,** Lastname' rather than 'Firstname Lastname' – @Li-ReDBox this should be an easy fix

**Comment by Li-ReDBox** [comment]
Yes. It is part of filter which kept comma after flipping parts. This [commit](https://github.com/modc08/mytardis/commit/5c7b1f0af337e04c894d595f050dfb63822efa06) has removed it. Let me I have misunderstood or there are other things.

**Comment by franksc** [comment]
:+1:
