### ISSUE TITLE
Slider widget for range queries

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#41]
If our search backend/functionality supports range queries (i.e. retrieve results within range x and y for a given search field), would be good to provide a 'range slider' widget to allow end users to define a range visually rather than typing in values. Something along the lines of this implementation using jQuery UI (which MyTardis already uses): https://jqueryui.com/slider/#range

It is anticipated this would form part of the advanced search form cf. #35 .

Example usage:

1. Show a search option 'Carbon date: [slider widget]'
2. User uses widget to select range 500 – 1500, runs query
3. Query is executed for Source.carbondate_years:[500 TO 1500]

UI consideration: should work on both desktop and mobile browsers

**Comment by shundezhang** [comment]
Done. please test.

**Comment by franksc** [comment]
Works as expected. Discussed with @shundezhang and decided on behaviour that if the slider is set to its min/max values (e.g. user doesn't change its default state), widget is not active and doesn't contribute a range query to the overall query executed by the advanced search form.
