### ISSUE TITLE
Enforce constraint of mandatory fields requiring a value when inserting records

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#42]
The MODC08 metadata schema defines some fields as mandatory (i.e. need to have a value) and some as optional (i.e. don't need to have a value). An error should be returned, and nothing should be saved, if an attempt is made to save/insert a record where any mandatory field doesn't have a value supplied.

**Comment by franksc** [comment]
When translating models to the database layer Django automatically adds an SQL NOT NULL constraint unless a model field has ```null=True```. This would seem to be a way of handling where a mandatory field doesn't have a value supplied; however, Django's [behaviour for string-based fields](https://docs.djangoproject.com/en/1.7/ref/models/fields/#null) is to record an empty value as 'empty string' rather than NULL, which means the NOT NULL constraint isn't violated.

(Django fields also have a ```blank=[True|False]``` option but this only applies to form-based input like the Django admin interface – you can manually/programmatically add objects (like we are planning to do using the deserialisation option) with empty values for fields with ```blank=False``` and they will be inserted/saved just fine.)

An option here may be to subclass/use replacements for Django's ```CharField``` and other string-based fields that do record empty values as NULL rather than 'empty string'.

**Comment by craigpatten** [comment]
This one-line django tweak forces model validation even when inserting data via the API.  It doesn't just enforce [blank](https://docs.djangoproject.com/en/1.5/ref/models/fields/#blank), it also handles [choices](https://docs.djangoproject.com/en/1.5/ref/models/fields/#choices) and anything else that form validation would pick up.

As this is a modification to django rather than mytardis, it would (at least to begin with) be an automated patch at time of installation.

modc08/django@5f56136604feea78c887a11b6291a277d3baa461

**Comment by franksc** [comment]
Have tested and can confirm this does bring [batch ingest script/process](http://github.com/modc08/store) to a screaming halt if you try to ingest metadata where a) a mandatory field is blank b) an invalid value is supplied for a field taking a fixed set of values c) value of wrong type is supplied e.g. a string where the field expects an integer.

A most elegant solution @craigpatten – can you please arrange for it to be patched/applied to an OAGR VM when it's spawned (then close this issue off)

**Comment by craigpatten** [comment]
✅

modc08/nectar-shell@4f0e34c0900b196dc806b26af7a73fb6d7e9c967
