### ISSUE TITLE
Clean up orphaned data on object store

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#43]
As discussed by @craigpatten in #30, implement periodic garbage collection/cleanup of data stored on the object store but no longer referenced by any files/representations in MyTardis.

**Comment by franksc** [comment]
Have discussed this functionality with ACAD and they suggested the periodic cleanup process run every week rather than every day/overnight (or even more frequently) – so in the event they delete some data files from MyTardis for which they don't have a copy elsewhere, there is still a window in which the files can manually be rescued from the object store before they are deleted from there.

**Comment by franksc** [comment]
An alternate option is to give ACAD a command line script to run this cleanup process on demand, rather than it running in the background periodically.

**Comment by millercathy** [comment]
Hi @franksc and @craigpatten Confirming where are we at on this? Did we agree for an on demand process?

**Comment by craigpatten** [comment]
Yes, it's mostly done as of modc08/store@031f51c. Will be finished ASAP.

**Comment by craigpatten** [comment]
✅ modc08/store@07cec3c

@franksc might want to kick the tyres before closing.

**Comment by franksc** [comment]
Testing:
1. Ingested (using store.py) a test experiment containing a dataset containing two files
2. Confirmed (using list.py) those files are in object store (inc. confirming MD5 hashes match source files)
3. Deleted one of those two files through MyTardis frontend
4. Ran clean.py to see what will happen. Indicates one file will be trashed from object store – confirmed the MD5 of the file to be deleted is that of the file we expected to be deleted
5. Ran clean.py -y to actually trash the file. Said it deleted the file; ran list.py again to confirm

:+1: :shipit:

**Comment by franksc** [comment]
Some further testing:
1. Ingested same test experiment again
2. One of the files just 'ingested' is already in object store so we should expect the datafile object/representation of the file created in MyTardis is just a reference to existing data file in object store – list.py confirms this by showing only two files in object store
3. Deleted one of those two files through MyTardis frontend where file is still in earlier experiment
4. As this file is still being referenced from MyTardis, shouldn't be trashed from object store; clean.py confirms this will not happen

**Comment by craigpatten** [comment]
Some improvements in modc08/store@9b1b7d9 &mdash; the cleanup script will tell you how many:
- references
- objects
- live references
- dead references (hopefully zero)
- unreferenced objects (&rarr; deletion)
