### ISSUE TITLE
Implement branding

### ISSUE THREAD

**Issue by millercathy** [modc08/modc08#47]
Further info to be provided

**Comment by franksc** [comment]
The default MyTardis favicon is for some reason a squirrel ... https://raw.githubusercontent.com/mytardis/mytardis/develop/tardis/tardis_portal/static/favicon.ico

Maybe we should replace this with one of our branding images, if it looks good scaled down to favicon size.

**Comment by franksc** [comment]
Done as part of https://github.com/modc08/mytardis/pull/11

We should maybe change favicon, per above?

**Comment by millercathy** [comment]
Happy for you to change favicon if time permits @franksc

**Comment by franksc** [comment]
No time to develop new favicon so have just commented this stuff out: modc08/mytardis@f3f657ccdfa1651caba2795069b57eb27b9841ea

Maybe we can revisit at a later date. Some URLs for future reference:
https://github.com/audreyr/favicon-cheat-sheet
http://stackoverflow.com/questions/4014823/does-a-favicon-have-to-be-32x32-or-16x16
