### ISSUE TITLE
Assign URL

### ISSUE THREAD

**Issue by millercathy** [modc08/modc08#48]
Pending decision about name of the repository/site.

**Comment by franksc** [comment]
@millercathy Are there rules/guidelines somewhere about domains *.adelaide.edu.au? (if we want to have that as part of our URL)

**Comment by millercathy** [comment]
@franksc https://www.adelaide.edu.au/webguide/about/domains/

**Comment by millercathy** [comment]
Hey @franksc as discussed can you do a bit more digging into this so we know what we have to do from Uni perspective - start getting the wheels in motion. Thank you.

**Comment by franksc** [comment]
oagr.adelaide.edu.au will be the public-facing URL.

This is just a CNAME alias to oagr.modc08.ersa.edu.au, which will be managed at the eRSA end to always point to the IP address of the current OAGR production VM.
