### ISSUE TITLE
Customise MyTardis Dataset view

### ISSUE THREAD

**Issue by craigpatten** [modc08/modc08#5]
Displaying ACAD metadata &mdash; how does the default layout (if any) differ from what is desired?

**Comment by franksc** [comment]
Dataset view needs to display its DOI if recorded in an associated parameter set – can probably adapt this from experiment view.

**Comment by millercathy** [comment]
Hi @Li-ReDBox
This tasks goes in tandem with #14 

Summary is as follows: @franksc correct me if I'm wrong!
*The Dataset view will display pipeline metadata including from the: Extract / Library / Sequence / Processing / Analysis tables
*It is possible for multiple pipelines to form a Dataset, i.e. there may be multiple 'sets' of Extract / Library / Sequence / Processing metadata and each 'set' or 'pipeline' will be displayed on a separate tab within the Dataset view
*The single or multiple pipelines will result in one Analysis
*The Source and Sample metadata will be presented in a separate view as per #14, which will be hyperlinked at the head of the record

So we need to:
[ ] Present Extract / Library / Sequence / Processing metadata on Dataset view where multiple records result in related 'sets' of metadata viewable on separate tabs
[ ] At the head of each tab, display and hyperlink to the title of Source and Sample records to be created in separate view as per #14 
[ ] Below the tabbed section, present metadata from Analysis table

See attached mock up as a guide
![dataset view](https://cloud.githubusercontent.com/assets/9669002/6033578/64cac3d6-ac67-11e4-8297-48b19ea6f2ac.png)

Please talk to @franksc for further info!
Thanks

**Comment by Li-ReDBox** [comment]
@franksc, do we have models of Extract / Library / Sequence / Processing? Is my task to merge your code in and then add more functions?

**Comment by franksc** [comment]
@Li-ReDBox see modc08/mytardis branch 'schematest' – this has models for Source, Sample, Extract etc as a separate Django app under tardis/apps/acad .

Branch 'views' builds on these models, and has a prototype of most of the combined source/sample view outlined in #14, plus an example of customising the MyTardis Dataset view to show some pipeline metadata via the relationship between the acad.analysis and tardis_portal.dataset models .

**Comment by Li-ReDBox** [comment]
I found them, thanks @franksc

**Comment by Li-ReDBox** [comment]
@franksc, I put branches view and schematest on top of modoc08, no error. I migrated models and loaded organism data. Just wondering if there are other data can be loaded? Or user has to create source, sample data var UI? Thanks

**Comment by franksc** [comment]
@Li-ReDBox I will prepare another fixtures file containing some made-up but representative/sensible metadata for a complete pipeline from Source -> Analysis.

**Comment by Li-ReDBox** [comment]
I have created a branch for this task: https://github.com/modc08/mytardis/tree/acad

**Comment by Li-ReDBox** [comment]
One dataset has one Analysis; 
One Analysis has one Processing; 
One Processing has one Sequence;
One Sequence has one Library;

Extract has one or more Library;
One Sample has one or more Extracts;
One Source has one or more Samples;

Please correct me if I am wrong

**Comment by franksc** [comment]
@Li-ReDBox This is all correct except 'One Analysis has one Processing'. One Analysis record is related to one or more Processing records, but each Processing record is related to only one Analysis record.

(PS on the MODC08 Google Drive there is a entity-relationship diagram for reference)

**Comment by Li-ReDBox** [comment]
Thanks, @franksc, I have printed it

**Comment by Li-ReDBox** [comment]
Is there an abstract drawing with all acad models in it? I am afraid that I cannot correctly figure out from the above mockup which section is from which model. Thanks.

**Comment by Li-ReDBox** [comment]
This is my current naive looking: ![a](https://cloud.githubusercontent.com/assets/3203171/6341476/b1053980-bc1a-11e4-84fa-af0ad76a409c.png)

**Comment by franksc** [comment]
@Li-ReDBox please see https://gist.github.com/franksc/e93a93018d0549579ea2 for prototype view used to generate the example image attached by Cathy above

(PS no comments on this horrendous code please – wasn't intended for public consumption ...)

**Comment by Li-ReDBox** [comment]
Thanks @franksc - the only comment :laughing:

**Comment by Li-ReDBox** [comment]
Thanks @franksc for providing code, I finally get something like the mockup in the code: https://github.com/modc08/mytardis/commit/833d91a8d0199b00943e541b7b2b0c016e30c596

Also, I added a function to get dataset from source: https://github.com/modc08/mytardis/commit/e92393bcb8b12a919af49ce3733f28fab1bb715a. Because I am still trying to understand the models so this get_dataset function can be quite wrong (very likely) and I labelled it as WIP and gave a warning message.

**Comment by franksc** [comment]
@Li-ReDBox I am not sure you are on the right track here – the idea is to customise the existing MyTardis dataset view (tardis/tardis_portal/templates/tardis_portal/view_dataset.html) to show ACAD metadata associated with the dataset, not create a separate view for this purpose.

modc08/mytardis@0d3ed1a6fc1168875440155983cf1eab832df551 shows an example of extending this view to show metadata from a field ('note') in the acad.Analysis record associated with the dataset.

Btw looking up datasets derived from a given Source (call it s) can be accomplished more simply with `Dataset.objects.filter(analysis__processing__sequence__library__extract__sample__source=s)`

**Comment by Li-ReDBox** [comment]
@shundezhang has made a few changes recently on views. Will branch-off from https://github.com/modc08/mytardis/tree/frontend to customise the existing MyTardis dataset view

**Comment by Li-ReDBox** [comment]
The latest Analysis model has removed note and added two other fields. I removed _note_ field and added placeholders for the two new fields. Please advise changes if needed. Thanks

Note: I accidentally committed to frontend not a new branch. I hope this does not cause any issue.
![dt](https://cloud.githubusercontent.com/assets/3203171/6436147/a758980c-c0fa-11e4-8b3c-01b3338f77e5.png)

**Comment by franksc** [comment]
Closing this as works as expected and only formatting/visual tweaks required
