### ISSUE TITLE
Need to be able to change experiment status from public metadata-only to public

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#50]
A desirable data publication workflow is:
- Ingest an experiment containing some datasets (with data files and ACAD schema metadata)
- Make this experiment and its contents public but with only metadata (not files) visible. This mints DOIs for the experiment and its datasets, so ACAD can cite this data in an associated research publication they are drafting without actually making the data files available (yet).
- At some later date (e.g. when the associated research publication is actually published) change experiment status to make data files now visible.
  - Can't change status back to public metadata-only or private after this (i.e. withdraw the data files from public availability) without doing some backend stuff as discussed in #27.

Or to put it another way: you can move an experiment's visibility status forwards (private -> public md only -> public), but not backwards.

However with the current functionality:
- Ingest an experiment
- Make experiment public metadata-only -- this gets you the DOIs
- Later change to public w/ files ... :x: **Can't, experiment is set to immutable as a result of DOI minting**

@Li-ReDBox can you please suggest how we might implement the desired behaviour as described above? Seems fiddly.

**Comment by Li-ReDBox** [comment]
@franksc, just to give you an update: I am investigating if https://github.com/modc08/mytardis/blob/modc08/tardis/tardis_portal/models/experiment.py#L46 can be used for this purpose. If this is not a solution, we may have to consider to add a switch.
Feel free to correct me and make suggestions.

**Comment by Li-ReDBox** [comment]
A possible solution:
- When sharing an experiment with self.public_access == _PUBLIC_ACCESS_METADATA, 'Public Metadata only (no data file access)'_, do not lock experiment. 
- UI allows access to be changed to PUBLIC_ACCESS_FULL only if an experiment with self.public_access == *PUBLIC_ACCESS_METADATA .
- Once an experiment in self.public_access == *PUBLIC_ACCESS_FULL, experiment is locked.

What do you think, @franksc ?

**Comment by franksc** [comment]
@Li-ReDBox I don't think that is going to work because:
- Under the DOI business rules, once a DOI is minted for a resource (e.g. experiment) the properties of the resource that inform citation, i.e. its metadata and files/contents, need to be unchanged i.e. experiment really should be made locked/immutable at this point. The only thing we want to be able to change when resource has DOI/is immutable is moving it forward from public (md) to public (everything). [yes I do realise this means it isn't strictly speaking immutable ...]
- We need to support going straight from private -> public (everything) as well as private -> public (metadata) -> public (everything) [sorry I should have made this explicit above]

Here is a hacky solution that seems to work:
- In tardis/tardis_portal/views.py `def share(request, experiment_id)`:

``` python
if experiment.public_access == Experiment.PUBLIC_ACCESS_METADATA:
    c['has_publicmd'] = True
```

And in tardis/tardis_portal/templates/tardis_portal/ajax/share.html L559:

``` python
{% if is_owner and has_change_permissions or has_publicmd %}
```

So, show the 'Change Public Access' button if we can change experiment (i.e. it isn't immutable) **or** we know it is published metadata-only.

Better ideas welcome ...

**Comment by Li-ReDBox** [comment]
@franksc this looks better because it sets _locked_ once an experiment is minted which complies better to minting rules. After minted, user is only allowed to change from md -> full no other direction. I will give it a go and see how it works.

**Comment by Li-ReDBox** [comment]
@franksc I followed your suggestions and made template checks of public_access_metedata which is straight forward. Then I messed around to remove access_none choice on server side when access is metedata only to stop going back. But found it was not as easy as doing it on front using js. Please check [commit](https://github.com/modc08/mytardis/commit/b9d7d3b23fd307267f4841c2999cbb8fe140c9a9) and feel free to criticise. Thanks.

**Comment by franksc** [comment]
Works for me @Li-ReDBox – after you take an experiment from private -> public (md) the Change Public Access button is still displayed but the private option is no longer available, and on switching to public (everything) Change Public Access disappears. :+1:

**Comment by Li-ReDBox** [comment]
I am not sure but I reckon this probably the original behaviour but we made it more strict if this is a good word to put it.
