### ISSUE TITLE
Performance testing

### ISSUE THREAD

**Issue by millercathy** [modc08/modc08#51]
As discuss in meeting 13/3/15

**Comment by craigpatten** [comment]
@shundezhang can you please:
- Load up a new OAGR instance and publish some dummy data (something meaty, perhaps several 1GB files)
- Get client VMs to simultaneously `wget`:
  - individual files
  - dynamically streamed tar files

Start with one client VM and try up to &hellip; "several" :blush:

Monitor the OAGR instance to see how we go with CPU and network usage. Yes, this is a fairly quick and informal test regime; it's just to see if anything behaves in an unexpected manner or if we need to measure something more rigorously.

Thanks :+1:

**Comment by shundezhang** [comment]
Test1: File size 1.1GB. 
Download URL: http://vm-modc08-20150427-102852.modc08.ersa.edu.au/api/v1/dataset_file/2/download
Clients: six m1.small cloud instances in SA zone. Server is also a m1.small instance in SA zone.
six concurrent single file downloads (running on 6 VMs): 'top' shows each gunicorn process uses 13% CPU and 1.5% RAM.
All finished in ~7 minutes.
Speed: ~10MB/s

Test2: Download the experiment which includes the above file as a tar ball (the experiment only has the above file and 2 very tiny txt files in the order of a few hundreds bytes.)
URL: http://vm-modc08-20150427-102852.modc08.ersa.edu.au/download/dataset/2/tar/
Performance is similar to the above.

If only download the single file with one client, the speed is ~26MB/s and the gnuicorn cpu usage can reach 45%.
If only download the tar file with one client, the speed is ~20MB/s and the gnuicorn cpu usage can reach 40%.

**Comment by shundezhang** [comment]
I also tried an experiment with 3G data files and observed similar behaviour as downloading 1G data file.
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by franksc** [comment]
Arbitrary benchmarking: I tried wget'ing the 1.1GB test file from my desk, deep within the Barr Smith library and on the slightly flaky UofA wifi, and managed an average speed of 2.14 MB/s.

**Comment by franksc** [comment]
I guess the next question is what, if any, conclusions can we draw from this performance testing e.g. should we bump to an m1.medium NeCTAR VM and double/increase the number of Gunicorn workers to handle more concurrent users?

**Comment by millercathy** [comment]
@craigpatten Can we close this today? We just need one line summary from you. Thanks!

**Comment by craigpatten** [comment]
Experience with various configurations of OAGR location and client location have shown that the system can produce acceptable streaming performance even when the participants (client, app, object store) are widely spread out. If CPU is shown to be a limiting factor in production then scaling up to larger instances is easy. Scaling horizontally would require more work.
