### ISSUE TITLE
backup and restore mechanisms

### ISSUE THREAD

**Issue by craigpatten** [modc08/modc08#52]
The only mutable state on the VM is held in the database, which needs to be regularly dumped into an object store (Swift, HCP, etc.).  The amount of data involved is quite small.

**Comment by millercathy** [comment]
Hi @craigpatten Does this issue cover the snapshot and relaunch work we discussed Friday? Cheers

**Comment by craigpatten** [comment]
@millercathy yes, this is the stuff that an ongoing monitoring system would hook into.

**Comment by Li-ReDBox** [comment]
As the first part of this task, I did a round of tests to find a suitable database to replace sqlite. This has been done and we have picked up the winner of backend database: postgresql.

To accommodate this backend, there are [few changes](https://github.com/modc08/mytardis/commit/953b011472dd9dbaddc7bb9f467bf18547c65a86) have been made. @franksc, could please check the change of acad.organism and other changes? Thanks.

During the tests, I manually installed postgres and driver psycopg2, made backend changes it passed my tests. psycopg2 can be installed globally or part of Django installation.

I think the installation of these two extra package on server should be incorporated into the deploy script. My time is up, so I do not want to mess up with it right now. Also the script needs to create at least a database user with correct privileges and creates a database which will later be referenced in settings.py.

``` javascript
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'acad_tardis',
        'USER': 'XXXX',
        'PASSWORD': 'xxxx',
        'HOST': '127.0.0.1',
        'PORT': '',
    }
}
```

Packages installed globally:

``` shell
sudo apt-get install python-psycopg2 postgresql
```

User(s):
Either through `psql` or `createuser` 

Mytardis has a module provides commands to [backup/restore](https://github.com/modc08/mytardis/blob/modc08/tardis/tardis_portal/management/commands/backupdb.py#L14). It is a wrapper of [pg_dump](https://github.com/modc08/mytardis/blob/modc08/tardis/tardis_portal/management/commands/backupdb.py#L131). Probably this is no better than Djano itself's commands for [backup/resotre](http://stackoverflow.com/questions/21049330/how-to-backup-a-django-db) in terms of our requirements.

Please feel free to make comments.

**Comment by franksc** [comment]
Postgres for the win!

modc08/mytardis@953b011472dd9dbaddc7bb9f467bf18547c65a86 looks fine to me, and should be able to be rolled into modc08 branch without affecting anything.

Dumping and loading data using Postgres is probably more efficient than Django's dumpdata/loaddata which relies on serialising/deserialising to JSON or similar – although as Li notes given our body of data we may not notice any performance difference.

Suggest testing with MyTardis' builtin database backup/restore commands to see if this works.

**Comment by Li-ReDBox** [comment]
Commands come from MyTardis are the wrappers of pg_dump for backup and psql -f for restore a backup. The backup command does not take extra switches. It only gets connection settings from settings.py. So before restore, an empty database with the same name has to be created. A normal user with all PRIVILEGES on the database can restore a backup but has one error for making comment, and a few warnings:

``` shell
psql:backups/backup_15032306.sql:23: ERROR:  must be owner of extension plpgsql
psql:backups/backup_15032306.sql:6116: WARNING:  no privileges could be revoked for "public"
psql:backups/backup_15032306.sql:6117: WARNING:  no privileges could be revoked for "public"
psql:backups/backup_15032306.sql:6118: WARNING:  no privileges were granted for "public"
psql:backups/backup_15032306.sql:6119: WARNING:  no privileges were granted for "public"
```

The [line](https://github.com/modc08/mytardis/blob/modc08_pg/tardis/tardis_portal/management/commands/backupdb.py#L163) sending password to pg_dump did not work in my test cases: I have to type in password. I think this has to be fixed.

**Comment by craigpatten** [comment]
Just had a chat with @Li-ReDBox and looked at the code. It's simpler to directly interface to the database dump/restore mechanisms. Instructing MT to do the same thing itself is a bit of a roundabout mechanism that doesn't actually buy anything and limits flexibility.

**Comment by Li-ReDBox** [comment]
[A snippet](https://gist.github.com/Li-ReDBox/21c548cc87ee7e2408e9) which I used in manual process to modify database backend. It might be inserted into sub/mytardis-prep/install.sh but I have not tested it.

During my manual set up procedure, I had to:
- kill the running django server
- run installation and setting change snippet listed above
- prepare MyTardis database: 

``` shell
bin/django syncdb --noinput
bin/django migrate --no-initial-data
/data/mytardis/mytardis-create-superuser $db_user $myt_password
# or as in other deployments:
# /data/mytardis/mytardis-create-superuser $myt_username $myt_password
```
- load data:

``` shell
bin/django loaddata initial_data
bin/django loaddata doi_schema
bin/django loaddata cc_licenses
```
- start server: `bin/django runserver 0.0.0.0:8080`
- backup users:
  sudo -u postgres pg_dumpall --globals-only > backups/globals.sql
- run backup: either `bin/django backupdb` in which case, I had to type in password, or run `pg_dump` as @craigpatten mentioned above
- psql -c backup.sql to restore

**Comment by Li-ReDBox** [comment]
1. backup the whole database in a [cron job](https://gist.github.com/Li-ReDBox/8dca63260260e9cfabdf)
2. [upload](https://gist.github.com/Li-ReDBox/8001cf910e1360c0bfe5#file-upload-retrieve-from-object-sore-L80) the database backup to object store 
3. [retrieve the latest backup](https://gist.github.com/Li-ReDBox/8001cf910e1360c0bfe5#file-upload-retrieve-from-object-sore-L93), then some script can run psql -f xxx when restoration is required.

Next: [clean.py](https://github.com/modc08/store/blob/master/clean.py) needs to leave these backups alone

These just are setting up components, I need to consult @craigpatten about how to get them into [store](https://github.com/modc08/store). 

Any comments are welcome

**Comment by Li-ReDBox** [comment]
_Below statements are based on the current [config.yaml](https://github.com/modc08/store/blob/master/config-example.yaml) structure; with an extra **db_backup** section which has the same keys as in **hcp** section only has different **base** value._

When files are uploaded var sync or upload (md5 mode), keys are set explicitly with hcp:base prefix. Backups will have db_backup:base prefix.

Current version of [clean.py](https://github.com/modc08/store/blob/master/clean.py#L32) grabs every file from the bucket for comparison to decide what to clean. If we use the below small change, backups should be able to be excluded from clean up if I have not missed something:

``` patch
diff --git a/clean.py b/clean.py
index c4377af..bfcb8df 100755
--- a/clean.py
+++ b/clean.py
@@ -29,7 +29,7 @@ def main():

     print "Listing objects...",
     object_details = {}
-    for o in hcp.list():
+    for o in hcp.list(config["hcp"]["base"]):
         object_details[o["name"]] = o
     objects = set(object_details.keys())
     print "done."
```

So, if backups and store are saved in the same bucket, make sure they all have `base` key in their configuration. If they will be in different buckets, clean.py does not need to be changed.

**Comment by franksc** [comment]
Storing OAGR data files and database backups in separate paths in the same bucket, e.g. datafiles/ and databases/, seems smart to me.

I wonder if in addition to 'retrieve latest backup' we may want a means to 'retrieve backup dated xxxx', to facilitate rolling back to a previous database state should this ever be necessary.

**Comment by Li-ReDBox** [comment]
@franksc, how often are you expecting database gets backed up? How accurate should date (timestamp) be filtered?

**Comment by Li-ReDBox** [comment]
Some code has been put into a new [branch](https://github.com/modc08/store/tree/db_backup)

**Comment by Li-ReDBox** [comment]
In terms of using dated condition, I had a bit of [play](https://github.com/modc08/store/commit/585beb4c9cda60207a386ae21af13cd58d5cc0ce). Not sure if it is what @franksc wanted.

**Comment by Li-ReDBox** [comment]
Currently I am using pg_dumpall to back up everything including all roles and drop/create commands. When run the backed up sql file var postgres role to restore, there are errors popping up which I have not found harmful:

``` shell
psql:dbbackup_20150408_093001:24: ERROR:  current user cannot be dropped
CREATE ROLE
ALTER ROLE
psql:dbbackup_20150408_093001:33: ERROR:  role "postgres" already exists
```

If this is a concern, we could find other more advanced methods for backing up/restoring or simply remove postgres role from backed up file.

**Comment by Li-ReDBox** [comment]
#### Current situation:
1. Deployment has been put into [fullstack branch of nectar-shell](https://github.com/modc08/nectar-shell/commits/fullstack). The _store_ sub manages restoring, set up jobs to backup database. All these actions interact with object store.
2. During the setup, a [modified settings.py](https://github.com/modc08/nectar-shell/blob/fullstack/sub/mytardis-prep/mytardis-prep.sh#L21) is used.
3. The configuration for connecting object store is downloaded from project's [storage](https://github.com/modc08/nectar-shell/blob/fullstack/sub/store/store.sh#L19). Like other secrets, it is an encrypted file in store.

#### Note:
1. [modc08_pg](https://github.com/modc08/mytardis/tree/modc08_pg) only has code to set up Postgres database, does not have current code.
2. When tests are done and merge fullstack branch to master, check and correct:
   - [modified settings.py](https://github.com/modc08/nectar-shell/blob/fullstack/sub/mytardis-prep/mytardis-prep.sh#L21)
   - [branch name](https://github.com/modc08/nectar-shell/blob/fullstack/run.sh#L5)
   - [storage config](https://github.com/modc08/nectar-shell/blob/fullstack/sub/store/store.sh#L19)

**Comment by franksc** [comment]
Simple test:
- Launched a VM using modc08_pg and fullstack branches
- On that VM added an experiment, dataset, files and ACAD metadata
- Let VM run for a while, waiting for cronjob to save db state and push to object store
- Launched another modc08_pg/fullstack VM with parameter to get 'latest' db state from object store
- New VM retrieved and loaded latest db state – extra experiment & other stuff present

:+1:

**Comment by millercathy** [comment]
Can we resolve #52, #61 and #65 by cob Tuesday 28 April??

**Comment by franksc** [comment]
I have merged modc08_pg branch into modc08, as its tweaks to Django models to accommodate Postgres work fine with sqlite as well.

**Comment by franksc** [comment]
@Li-ReDBox Is there any further development required/in progress here?

**Comment by Li-ReDBox** [comment]
DB part I cannot think of any at the moment. For settings, probably you want to remove some `sed`'s and update settings.py. (on slow link)
