### ISSUE TITLE
'X' to remove dataset from experiment

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#56]
In the experiment view for an unpublished/non-locked experiment there should be 'X' links in the top-right corner of each dataset box (right hand column) to detach the dataset from the experiment. However, on loading the experiment view page these 'X's appear briefly then disappear.

Example: http://vm-frontend-tweaks-20150316-130458.modc08.ersa.edu.au/experiment/view/4/

This has worked in the recent past as shown in this screenshot from issue #30: https://github.com/modc08/modc08/issues/30#issuecomment-74019536

I tested on OS X Safari and Firefox, Shunde tested on OS X Chrome and Cathy tested on Windows Internet Explorer (I think) and we all encountered this issue. Weirdly I am encountering same issue with a test install of MyTardis 3.6 untouched by our customisations.

The relevant template portion seems to be https://github.com/mytardis/mytardis/blob/a8cf343d5265577eb66177d089c4e9f7d9dabe25/tardis/tardis_portal/jstemplates/tardis_portal/dataset_tile.html#L22

**Comment by shundezhang** [comment]
that delete icon 'X' is visible when the dataset is attached to multiple studies. if it is only attached to one dataset, you can't detach it, hence no 'X' is shown.

**Comment by franksc** [comment]
Well that was obvious. Good sleuthing @shundezhang

**Comment by franksc** [comment]
The 'X' does not respect the condition of experiment being immutable – it should not be possible to detach a dataset from an experiment that is immutable/published.
1. Don't show 'X'-es for any dataset if experiment is set to immutable
2. If attempt is made to detach a dataset from an experiment, this should fail (with error message popup 'Can't detach dataset: experiment is immutable')

**Comment by franksc** [comment]
Testing:
- Dataset is attached to only one experiment = no 'X' to remove :white_check_mark: 
- Dataset is attached to multiple experiments = 'X' to remove :white_check_mark: 
- Experiment is immutable = no 'X's to remove datasets :white_check_mark: 
- Attempt to remove dataset from public experiment = error message popup :white_check_mark:
