### ISSUE TITLE
Wrong output filename when direct downloading outside of browser / 'Remote file name has no length' error

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#57]
When downloading a MyTardis individual file, dataset tar or experiment tar via URLs with form mytardisexample.com/api/v1/dataset_file/_id_/download or .../download/_dataset_|_experiment_/_id_/tar/ outside of the browser window navigating the repository site e.g. on the command line via wget or curl, the output filename is incorrect. Also, curl returns a 'Remote file name has no length' error when trying to download dataset and experiment tar URLs with a trailing slash. (The URL linked from a MyTardis blue 'tar' download button has the trailing slash)

E.g using wget _url_:
- http://vm-frontend-tweaks-20150316-130458.modc08.ersa.edu.au/api/v1/dataset_file/4/download outputs to filename 'download'
- http://vm-frontend-tweaks-20150316-130458.modc08.ersa.edu.au/download/dataset/4/tar/ outputs to filename 'index.html'
- http://vm-frontend-tweaks-20150316-130458.modc08.ersa.edu.au/download/experiment/3/tar/ outputs to filename 'index.html'

E.g. using curl -O -L _url_:
- http://vm-frontend-tweaks-20150316-130458.modc08.ersa.edu.au/api/v1/dataset_file/4/download outputs to filename 'download'
- http://vm-frontend-tweaks-20150316-130458.modc08.ersa.edu.au/download/dataset/4/tar/ returns a 'Remote file name has no length' error
  - http://vm-frontend-tweaks-20150316-130458.modc08.ersa.edu.au/download/dataset/4/tar (without the trailing slash) outputs to filename 'tar'
- http://vm-frontend-tweaks-20150316-130458.modc08.ersa.edu.au/download/experiment/3/tar/ returns a 'Remote file name has no length' error
  - http://vm-frontend-tweaks-20150316-130458.modc08.ersa.edu.au/download/experiment/3/tar (without the trailing slash) outputs to filename 'tar'

(NB tested with wget 1.15 and curl 7.37.1 on OS X)

**Comment by franksc** [comment]
This seems to be a bug in MyTardis core as also evident with 3.6 release – we should probably push our fix upstream

**Comment by craigpatten** [comment]
This is just a case of using the appropriate command-line parameters to instruct the client to take notice of the [Content-Disposition](https://tools.ietf.org/html/rfc2183) response header.

For curl: use [-J / --remote-header-name](http://curl.haxx.se/docs/manpage.html#-J).

For wget: use [--content-disposition](http://www.gnu.org/software/wget/manual/html_node/HTTP-Options.html).
