### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by millercathy** [modc08/modc08#59]
Provide documentation for handover including:
- System architecture diagram
- HCP specs (re security etc as we discussed)

**Comment by franksc** [comment]
@craigpatten MyTardis component architecture diagram might be a decent starting point: http://mytardis.readthedocs.org/en/develop/architecture.html

**Comment by millercathy** [comment]
Thanks @craigpatten for draft doco discussed this morning. Some additions and revisions required as per communication from @franksc
