### ISSUE TITLE
MyTardis/Django production deployment

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#61]
Looking through MyTardis' Django settings.py there would seem to be some settings we will want to change for production deployment:
- Change DEBUG from True to False
- Change SECRET_KEY to something unique to our deployment
- Change ALLOWED_HOSTS to something other than '*'

Anything else?

**Comment by franksc** [comment]
Here is some Python to copy and paste for generating a Django SECRET_KEY: https://gist.github.com/ndarville/3452907#file-secret-key-gen-py-L22

**Comment by franksc** [comment]
See also the Django docs under 'Deploying Django': https://docs.djangoproject.com/en/1.5/howto/deployment/

**Comment by franksc** [comment]
If you set DEBUG = False, MyTardis craps out (any page/URL) with less than helpful error message 'A server error occurred.  Please contact the administrator.' Examining django.out log indicates this is a HTTP 500 error relating to Django not finding a static asset (jQuery).

Need to get Django to collect together static files (CSS, Javascript libs etc) under `/data/mytardis/mytardis/static`: `bin/django collectstatic --noinput`

And update Nginx config to serve [hostname]/static/\* from this directory:

``` nginx
location /static/ {
    alias /data/mytardis/mytardis/static/;
}
```

(then restart Nginx)

**Comment by franksc** [comment]
With DEBUG = False Django will pay attention to the [ALLOWED_HOSTS](https://docs.djangoproject.com/en/1.5/ref/settings/#allowed-hosts) setting. Not sure if a valid setting for production would be 'oagr.adelaide.edu.au', or '.modc08.ersa.edu.au' (i.e. all subdomains under modc08.ersa.edu.au), or both.

**Comment by franksc** [comment]
[At the moment](https://github.com/modc08/nectar-shell/blob/master/sub/mytardis-prep/install.sh#L87) we are running MyTardis using the Django builtin web server, which the [docs](https://docs.djangoproject.com/en/1.5/ref/django-admin/#django-admin-runserver) make clear is not suitable for a production/real-world deployment.

Using nginx for static assets and gunicorn for the Django side seems a popular option for deploying Django apps, and Grischa has advised it is used for the Store.Synchrotron deployment of MyTardis.

@craigpatten and @shundezhang, do you think this seems suitable?

**Comment by franksc** [comment]
nectar-shell branch [fullstack-gunicorn](https://github.com/modc08/nectar-shell/tree/fullstack-gunicorn/) implements the stuff above: DEBUG, ALLOWED_HOSTS and SECRET_KEY settings and deployment using nginx+gunicorn, using the pre-rolled gunicorn_settings.py that comes with MyTardis.

**Comment by franksc** [comment]
Pre-rolled gunicorn_settings.py uses Gunicorn asynchronous worker type gevent, which causes problems with DOI minting (noted by me) and tar downloading (noted by @craigpatten).

Running with worker type 'sync' appears to resolve these issues, but need to consider how many workers of this type are needed to handle the number of concurrent users and performance we need for production deployment.

**Comment by millercathy** [comment]
Can we resolve #52, #61 and #65 by cob Tuesday 28 April??

**Comment by franksc** [comment]
@craigpatten noted the [Gunicorn docs](http://gunicorn-docs.readthedocs.org/en/latest/deploy.html) indicate if you want do streaming requests/reponses you need to use one of the asynchronous worker types. :angry:

**Comment by franksc** [comment]
@craigpatten's comment from modc08/mytardis@662bb2e89ca35217598e7b17198954bac87adba8:

> gevent breaks things in a complex way that looks too time-consuming to fix within our current schedule.
> 
> A sufficient number of sync workers (16 is an arbitrary choice) is (i) easy to reason about, because it doesn't involve kludg^H^H^H^H^Hpatching the python runtime, and (ii) probably a decent first estimate for handling the site load.
> 
> Streaming still works with sync workers, it's just not normally recommended because long downloads will tie up a sync worker for the duration of the download. However, in this case, a few concurrent downloads will easily saturate the throughput of a NeCTAR m1.small VM long before the 16 worker limit is reached. If this VM flavour and worker count prove inadequate, both can easily be reconfigured.

**Comment by Li-ReDBox** [comment]
I did a bit work followed suggestions from @craigpatten, I created a _"cleaner"_ settings.py which is in object store: settings_cleaning.py.enc. This is referenced as: [SPECIAL_SETTINGS_URL](https://github.com/modc08/nectar-shell/blob/9d9d9be283395f707f8e0ab6767a9b7e27dbe76d/sub/mytardis-prep/mytardis-prep.sh#L34). It is also used in [fullstack-gunicorn](https://github.com/modc08/nectar-shell/blob/fullstack-gunicorn/sub/mytardis-prep/mytardis-prep.sh)

At the same time, a bit [template work](https://github.com/modc08/nectar-shell/blob/9d9d9be283395f707f8e0ab6767a9b7e27dbe76d/sub/mytardis-prep/installsh). It might be useful or not, I am not sure. On instances, original install.sh is renamed as install.sh.back which can be compared with install.sh created by this template.

By eye-balling the testing instances, the setting.py and installsh template passed tests.

**Comment by franksc** [comment]
@Li-ReDBox Moved cleaning up settings.py customisation into #68

**Comment by franksc** [comment]
Closing this as mytardis modc08 and nectar-shell fullstack-gunicorn set up MyTardis settings.py and nginx+gunicorn config for production readiness.
