### ISSUE TITLE
Domain name management for production VM

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#62]
The public-facing URL for OAGR will be oagr.adelaide.edu.au, which is just an alias to oagr.modc08.ersa.edu.au (cf. #48). We need to ensure oagr.modc08.ersa.edu.au always resolves to the IP of the current production deployment of OAGR, as it inevitably changes over time.

A simple solution would be for a newly deployed OAGR VM to declare 'I am the new production instance' and update oagr.modc08.ersa.edu.au to point to its IP address on NeCTAR.

This would mean any manual or automatic process to kill and respawn the production instance (e.g. if it crashes) would not need to handle updating the oagr.modc08 domain.

@craigpatten Thoughts?

**Comment by franksc** [comment]
As discussed with @craigpatten, we also want some means to manually update the resolution of oagr.modc08.ersa.edu.au to a specified target IP address – ideally something ACAD could access/run themselves.

A command line script will probably suffice, e.g. `> update-oagr-ip [some IP address]`

**Comment by craigpatten** [comment]
[ pinged @franksc over email ]

**Comment by millercathy** [comment]
@craigpatten Can we close this?

**Comment by craigpatten** [comment]
oagr.org.au is managed dynamically — an instance named X will claim X.oagr.org.au. If X == `www` then it's production. Dev/test instances can be called anything other than `www`.
