### ISSUE TITLE
Establish read-only credentials for frontend HCP access

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#63]
Establish a separate set of credentials that permit read-only access to the HCP object store, for use by the OAGR MyTardis frontend – so the frontend can get data and serve it to end users but not put anything in.

Maintain the existing read-write credentials so backend services like http://github.com/modc08/store can upload to object store.

**Comment by craigpatten** [comment]
There is a new ACAD HCP tenant with two namespaces: one for bulk data ("data") and one for database backups ("backups").

A few different sets of credentials have been generated following the principle of least privilege:
- read-only access to bulk data (MyTardis)
- read/write access to database backups (non-destructive writes only) (MyTardis VMs)
- read/write access to bulk data (non-destructive writes only) (ACAD staff)
- superuser access to everything (ACAD staff)

When I say "non-destructive" I mean you can add objects but you cannot overwrite or delete.

The last account should rarely be necessary.

**Comment by franksc** [comment]
I believe the OAGR settings.py needs to be updated to use the 'read-only access to bulk data' credentials

**Comment by millercathy** [comment]
Hi @craigpatten Can we wrap this up by Monday 25/5 for build on Tuesday 26/5? Thanks

**Comment by craigpatten** [comment]
@millercathy yup

**Comment by craigpatten** [comment]
Fixed.
