### ISSUE TITLE
Changing experiment from public (md only) -> public (everything) needs to update DOI metadata

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#64]
Customisations made in #50 allow an experiment to be 1. progressed from private -> public (metadata only), at which point a DOI is minted and experiment becomes publicly visible but without public access to its files 2. subsequently progressed to public (everything) where the files become accessible.

However, when the DOI is minted as part of step 1 no licence has been applied to the experiment data+metadata, as data files are not being made available at this point – therefore the DataCite XML provided to ANDS Cite My Data service as part of minting the DOI does not contain any `<rights>` element/info (cf. #19). When the experiment is progressed to public (everything) the files/metadata are made available under a selected licence, but the metadata for the already-minted DOI (as provided to Cite My Data and stored at its end) is not updated to reflect this change in licensing/rights status.

Progressing an experiment from public (md) to public (everything) should regenerate the Datacite XML for the experiment and any child datasets\* to include the `<rights>` element and info (the metadata will otherwise be unchanged), and update the metadata stored at Cite My Data against the associated DOI. Cite My Data provides an 'update a DOI' REST endpoint (`https://services.ands.org.au/doi/1.1/update.[json|xml]`) to facilitate this.

(\* Where the experiment being changed is the 'direct parent' of the dataset – don't do anything if dataset has a different experiment in its Dataset.experiment field)

**Comment by franksc** [comment]
WIP modc08/mytardis@d712b895548f99a3e43a9b1e4e8e4d2e6470fba4

**Comment by franksc** [comment]
A side note: the [Cite My Data technical doc](http://ands.org.au/services/cmd-technical-document.pdf) says the Update DOI endpoint allows a client to 'update the URL only, metadata only, or both the URL and metadata' (3.11.3) and the `&url` URL parameter is only required when you want to update the URL

... but I found it returned an error when attempting to update a DOI (with `&doi` URL parameter) without the `&url` parameter as well:

``` json
  "response": {
    "app_id": "[redacted]",
    "doi": null,
    "message": "The provided URL does not belong to any of your registered top level domains. If you would like to add additional domains to your account please contact services@ands.org.au. ",
    "responsecode": "MT014",
    "type": "failure",
    "url": "",
    "verbosemessage": "URL not permitted."
  }
}
```

To work around this we always provide the `&url` parameter with the current URL of the resource – so not really 'updating' the URL.

**Comment by franksc** [comment]
Done and merged into modc08 branch with modc08/mytardis@f019fe292c8163edc92c892babfac3a3b2e1a064

**Comment by franksc** [comment]
Production-ready deployment has exposed some problems with the way this functionality is called. modc08/mytardis@7c0119029356a21ea9538322663d8b4a88214b86 disables calling update_doi while I investigate and work out a fix/improvement.

**Comment by franksc** [comment]
The problem here appears to be calling the update_doi() method in ands_doi.py, which is similar to existing methods but posts its rendered DataCite XML to Cite My Data's 'update this DOI' endpoint. I believe this method works as expected.

The 'special' behaviour we want: if in the rights/sharing popup we are moving from public (metadata only) to public (everything) and the experiment has a DOI, we want to call update_doi() rather than get_or_mint_doi().

This change to hooks.py:  https://github.com/modc08/mytardis/commit/f019fe292c8163edc92c892babfac3a3b2e1a064#diff-5819a8026cbda636667eaab662417d1cR69 appeared to work okay when running on Django builtin web server, but failed when running on gunicorn.

@Li-ReDBox Any ideas?

**Comment by Li-ReDBox** [comment]
@franksc, I yet find any clue by just looking at commits you listed in this issue. Which branch should I look at? Do you think if it is possible with threading?

**Comment by franksc** [comment]
@Li-ReDBox This was done on branch doi-update https://github.com/modc08/mytardis/commits/doi-update

You raise a good point that maybe it was use of gunicorn gevent/asynchronous workers that was messing this up – I will do some testing and update this issue

**Comment by Li-ReDBox** [comment]
@franksc, sounds good

**Comment by franksc** [comment]
This is the behaviour we want:

Change experiment from private -> public (everything) – call get_or_mint_doi() to mint and save DOI.

Change experiment from private -> public (metadata) – call get_or_mint_doi() to mint and save DOI.

Change experiment from public (metadata) -> public (everything) [it already has a DOI at this point] – call update_doi() to render DataCite metadata again and POST to Cite My Data endpoint to update the metadata stored at Cite My Data end for this DOI.

This at first glance appears to work, on both Django dev server and Gunicorn with sync workers:

``` patch
diff --git a/tardis/tardis_portal/models/experiment.py b/tardis/tardis_portal/models/experiment.py
index de5f099..5a9d106 100644
--- a/tardis/tardis_portal/models/experiment.py
+++ b/tardis/tardis_portal/models/experiment.py
@@ -218,7 +218,12 @@ class Experiment(models.Model):
             doi_url = settings.DOI_BASE_URL + self.get_absolute_url()
             from tardis.tardis_portal.ands_doi import ExperimentDOIService
             doi_service = ExperimentDOIService(self)
-            doi_service.get_or_mint_doi(doi_url)
+            if doi_service.get_doi() and self.public_access == Experiment.PUBLIC_ACCESS_FULL:
+                doi = doi_service.get_doi()
+                logger.info("calling update_doi")
+                doi_service.update_doi(doi, doi_url)
+           else:
+                doi_service.get_or_mint_doi(doi_url)
```

But because get_or_mint_doi() calls _mint_doi() which calls Experiment.save() to save the experiment to be locked/immutable (`self.obj.save(update_fields=['locked'])`), taking an experiment from private -> public (everything) mints a DOI as expected but then straight after calls update_doi, unnecessarily.

We need to _only_ call update_doi() when going from public(md) -> public(everything).

@Li-ReDBox can you please apply a fresh pair of eyes to try to get this working as expected. vm-gunicorn-doi-20150518-171723 is running on Django server, vm-gunicorn-doi-20150520-104446 is on Gunicorn.

(No doubt the solution is blindingly obvious ...)

**Comment by Li-ReDBox** [comment]
@franksc, if I understood the question correctly, we can avoid calling undate_doi() when go from private to public by checking update_fields to identify if it is called by ands_doi after successfully minted a doi to lock an experiment. If it is just locking, do not call mint_doi(). Below is my debugging code which is different to the [commit](https://github.com/modc08/mytardis/commit/4b5c563e98a0c487f315e3ba7a18df656e7643bd).

``` patch
diff --git a/tardis/tardis_portal/models/experiment.py b/tardis/tardis_portal/models/experiment.py
index de5f099..75579de 100644
--- a/tardis/tardis_portal/models/experiment.py
+++ b/tardis/tardis_portal/models/experiment.py
@@ -75,10 +75,20 @@ class Experiment(models.Model):
         app_label = 'tardis_portal'

     def save(self, *args, **kwargs):
+       logger.info("Saving experiment")
+       logger.info(kwargs)
+       #logger.info(self.__dict__)
         super(Experiment, self).save(*args, **kwargs)
         from .hooks import publish_public_expt_rifcs
         publish_public_expt_rifcs(self)
-        self.mint_doi()
+       #TODO: or just check if kwargs has key, because so far there is only one special case when doi has been mintted.
+       #Or check more conditions, access?
+        if 'update_fields' in kwargs and 'locked' in kwargs['update_fields']:
+           logger.info("Successfully minted, locking, so skip")
+            #self.mint_doi()
+       else:
+           logger.info("Normal saving, trigger minting")       
+            self.mint_doi()

     def delete(self, *args, **kwargs):
         if self.locked:
@@ -213,12 +223,20 @@ class Experiment(models.Model):
         return None

     def mint_doi(self):
+       #TODO: if we can do a dirty check on public_accesss, things will be easiser
         if settings.DOI_ENABLE and \
            self.public_access != Experiment.PUBLIC_ACCESS_NONE:
             doi_url = settings.DOI_BASE_URL + self.get_absolute_url()
             from tardis.tardis_portal.ands_doi import ExperimentDOIService
             doi_service = ExperimentDOIService(self)
-            doi_service.get_or_mint_doi(doi_url)
+            #doi_service.get_or_mint_doi(doi_url)
+           doi = doi_service.get_doi()
+            if doi and self.public_access == Experiment.PUBLIC_ACCESS_FULL:
+               logger.info("DOI exists, access now is public, calling update_doi")
+                       doi_service.update_doi(doi, doi_url)
+            else:
+               logger.info("go old route which actually now is minting")
+                doi_service.get_or_mint_doi(doi_url)

 class Author_Experiment(models.Model):
```

**Comment by franksc** [comment]
@Li-ReDBox have tested and this appears to work.

Of course this is the approach I tried but it didn't work for me ... :angry:
