### ISSUE TITLE
Restrict access to Elastic HQ plugin

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#65]
The current OAGR build process installs the [Elastic HQ plugin](http://www.elastichq.org) as part of setting up the ElasticSearch component. This has proved useful for debugging/reviewing search indexing and would be handy to maintain in production, but we would want to restrict access to only trusted people.

@shundezhang What do you think this is the best way of doing this? Just apply basic HTTP authentication using some username/password combo?

**Comment by millercathy** [comment]
Can we resolve #52, #61 and #65 by cob Tuesday 28 April??

**Comment by shundezhang** [comment]
I have changed elasticsearch to only listen on localhost, and set up nginx as a proxy running on port 9000 passing requests to elasticsearch's port 9200. To use the plugin, use this link "http://HOSTNAME:9000/_plugin/HQ". It is protected by simple authentication. The username is modc08 and the password is the f-word we use in mytardis. For the production server, we can also set up firewall rules to only open port 9000 to uni adelaide IP range (129.127._._) and eRSA office IP range (172.16.5.*).
