### ISSUE TITLE
Search with 0 results raises DatabaseError when using Postgres

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#66]
On an OAGR VM using PostgreSQL rather than sqlite (built using mytardis/modc08_pg and nectar-shell/fullstack branches), a search that returns 0 results raises a DatabaseError exception based on an SQL syntax error:

```
syntax error at or near ")"
LINE 1: ...lectedby" FROM "acad_source" WHERE (lower(id) IN ()) ORDER B...
```

**Comment by shundezhang** [comment]
fixed in the above commit

**Comment by franksc** [comment]
:+1:
