### ISSUE TITLE
Search index study_author not updating as expected

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#70]
The `study_author` search index indexes the authors of each experiment/study. It seems while changes to an experiment title, publication year etc are reindexed pretty much straight away, this author names index is only being populated for an experiment when its status changes from private to public.

@shundezhang advises a manual reindex from the command line sees `study_author` populated/reindexed for all experiments (private and public). We could just run this periodically (cronjob), but this not a great solution and potentially confusing for OAGR admin/ACAD as most updates to an experiment will be reindexed straight away, but changes to an experiment's authors will only be reindexed periodically.

@shundezhang Can you please look into whether we can get study_author to be reindexed whenever an experiment's authors are edited, as with other experiment fields/properties.

**Comment by shundezhang** [comment]
This is how an experiment is saved:
- remove all existing authors
- save experiment (into experiment table)
- save authors (into author table)

reindex happens in step 2, where no authors exist. That's why authors are not indexed. (Actually the author index is cleared out every time the experiment is saved.)

**Comment by franksc** [comment]
Editing authors in an experiment sees study_author updated/reindexed straight away.

Also, creating a new experiment sees its authors indexed into study_author straight away.

:+1:
