### ISSUE TITLE
Dataset view should display large number of pipelines better

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#72]
The current custom dataset view puts each pipeline (a block of metadata from ADAD models source, sample etc) in a separate div, and uses [Bootstrap navigation tabs](http://getbootstrap.com/components/#nav-tabs) to switch (show/hide) between them.

If you have more tabs than can fit horizontally across the page/column, it looks weird:

![screen shot 2015-05-13 at 11 42 39](https://cloud.githubusercontent.com/assets/8837821/7602699/095117ce-f967-11e4-820e-bc3b4ef1e81e.png)

modc08/mytardis@b253cae17f0d1ac4ede58819c7ef0a26715c6128 implements behaviour that for a large number of pipelines (I arbitrarily chose greater than 7), show a dropdown picker for pipelines rather than tabs.

Other ideas welcome ...

**Comment by millercathy** [comment]
Great work @franksc. This looks much neater. @craigpatten I'm happy with this unless you see any other possibilities? Cheers.

**Comment by franksc** [comment]
ACAD have okayed this; merged into modc08 as part of modc08/mytardis@27d646c531ee29b0e360e1758a52a7c6f4a59257
