### ISSUE TITLE
OAGR does not restart after VM restart

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#75]
It would appear that if an OAGR VM is shut down and restarted in NeCTAR, this initiates the https://github.com/modc08/nectar-shell build process again and it fails when trying to [`git clone` the OAGR repository](https://github.com/modc08/nectar-shell/blob/master/sub/mytardis-prep/install.sh#L9) (`fatal: destination path 'mytardis' already exists and is not an empty directory`).

Getting OAGR/MyTardis running again requires ssh'ing in and manually restarting the web server process (Django builtin server or gunicorn).

It would be ideal for an OAGR VM to more cleanly handle a shutdown/restart and end up in same state i.e. with OAGR/MyTardis running.

**Comment by craigpatten** [comment]
Fixed.
