### ISSUE TITLE
Ongoing record management - insertion, modification, etc.

### ISSUE THREAD

**Issue by craigpatten** [modc08/modc08#8]
Initial bulk data upload is of course not the only use case; investigate the mechanism for ongoing management of data &mdash; insertion, modification, etc.

Evaluate impact on DOIs, specifically regarding the immutability of published data.

**Comment by franksc** [comment]
Delete functionality will be implemented in #30.

Experiment and dataset metdata (title, authors etc) can be edited via MyTardis frontend until DOI is minted and resource is set to locked/immutable.

As under current workflow ACAD provenance/pipeline metadata is provided by way of ingesting from an external source file rather than directly entering through frontend, there is presently no frontend functionality for editing this metadata once ingested/created.

**Comment by franksc** [comment]
Django's [default update-or-insert behaviour](https://docs.djangoproject.com/en/1.5/ref/models/instances/#how-django-knows-to-update-vs-insert) means if an attempt is made to save a record where one with the same primary key already exists, the existing record will be updated from the values of the new one. So if Bastien ingests a dataset with ACAD metadata including a Source record with pk=1234, and then later Laura ingests another dataset with metadata also including a Source record with pk=1234, the MyTardis Source table will be updated with Laura's data for this record.

Not sure if this is the behaviour we want, or if we want to throw an error in response to or just ignore attempts to update existing records.

**Comment by millercathy** [comment]
@franksc This is on our agenda for our meeting this Friday 6/2 (not that question specifically but we can include it in the discussion)... I'd suggest option 2 above but let's confirm Friday?

**Comment by franksc** [comment]
Have discussed with Cathy and determined building MyTardis frontend forms/functionality to edit ACAD provenance/pipeline metadata is probably overkill.

Django's update-or-insert behaviour means it will be possible for ACAD to if necessary update existing metadata records by ingesting an Excel source file as detailed in #24. The Django admin backend is available should there be a burning need to fix a typo/minor error.

Also, quality control measures will be applied to the Excel source file template (e.g. dropdowns for fields which take a fixed set of options) to limit the potential for invalid/incorrect metadata being entered.
