### ISSUE TITLE
Fix settings.py DOI_BASE_URL

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#82]
In MyTardis settings.py, DOI_BASE_URL is used in constructing a resolution URL for a resource for which a DOI is being minted – 'http://' + hostname + '/path/to/resource/' = resolution URL.

At present 'hostname' is determined using `os.getenv("HOSTNAME")`, which only works if environment from which the MyTardis web server process was launched has set HOSTNAME – hence the preceding `HOSTNAME="`hostname`"` in https://github.com/modc08/nectar-shell/blob/master/sub/mytardis-prep/install.sh#L87

`socket.gethostname()` would seem a better way.

**However** ... in production we want the resolution URL of a minted DOI to be http://oagr.adelaide.edu.au/path/to/something/, rather than use the actual system hostname oagr.modc08.ersa.edu.au .

So, maybe replace `os.getenv("HOSTNAME")` with some 'REPLACE ME' string, and in install.sh add yet another sed command to replace this with 'oagr.adelaide.edu.au' if our hostname is oagr.modc08.ersa.edu.au, or otherwise just the system hostname.

Your suggestions please.

**Comment by craigpatten** [comment]
The base DOI URL is now part of the `settings.py` parameterisation.
