### ISSUE TITLE
Production OAGR settings.py

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#83]
An OAGR build designated as being for production/real-world use, that grabs the oagr.mod08.ersa.edu.au domain, will need some special values in its MyTardis settings.py:
- DOI_BASE_URL = **http://oagr.org.au/** (cf. #82)
- Cite My Data credentials for real DOI minting (cf. #55)
- ALLOWED_HOSTS to include oagr.modc08.ersa.edu.au and **oagr.org.au**
- Possibly we only want the production build to be reading and writing from the 'real data' HCP tenant, using credentials from #63 – with other builds continuing to use the dev tenant?

**Comment by millercathy** [comment]
Hi @craigpatten Can we wrap this up by Monday 25/5 for build on Tuesday 26/5? Thanks

**Comment by craigpatten** [comment]
@millercathy yup

**Comment by craigpatten** [comment]
[settings.py](https://github.com/modc08/nectar-shell/blob/master/sub/mytardis-prep/settings.py) is now a jinja2 template in GitHub, parameterised by [environment variables](https://github.com/modc08/nectar-shell/blob/master/user-data.sh) during installation.

**Comment by craigpatten** [comment]
The default build coming out of slack (minus some backup/restore functionality which is still being merged in) is now production-ready.
