### ISSUE TITLE
Search synonym Neanderthal for Neandertal

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#85]
In OAGR metadata we are using the spelling 'Neandertal' for [these guys](http://en.wikipedia.org/wiki/Neanderthal). However, many end users will probably use the alternate spelling 'Neanderthal' in querying, and this should retrieve the same results.

Can we use Elasticsearch [synonyms](https://www.elastic.co/guide/en/elasticsearch/guide/current/synonyms.html) so search term 'Neanderthal' is treated as if it were 'Neandertal'? (E.g. for queries 'africa Neanderthal' and 'organism:Neanderthal')

(There are potentially other useful search synonyms that would enhance searching for end users.)

**Comment by shundezhang** [comment]
@franksc Just want to clarify the use case. Do OAGR always use the correct spelling 'Neandertal'? If yes, in the index there is only 'Neandertal'. I think Elasticsearch synonyms takes effect when the index is built: it will index a word and its synonyms into a single form. However this is not our case. If we want to return 'Neandertal' when users spell it differently, the easier way is to replace the alternate spelling with our correct spelling in the query so it will always be searching the correct word.

**Comment by millercathy** [comment]
@shundezhang your summary sounds correct to me

**Comment by franksc** [comment]
The record in ACAD Organism table will have common name (Organism.common) 'Neandertal' – we use the Genbank common name from [NCBI taxonomy record](http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=63221).

However it is possible metadata in other places, such as Experiment.description, will use 'Neanderthal'. (I think ACAD tend to use/prefer 'Neandertal' spelling, but don't quote me on that.)

The ideal behaviour is queries for 'Neandertal' and 'Neanderthal' will retrieve same results. I.e. if we had a Source with organism common name 'Neandertal' and an Experiment with 'Neanderthal' somewhere in its .description, either query would retrieve two results – rather than just the one which matches the spelling used in the query.

Looking at Elasticsearch docs for [Formatting Synonyms](https://www.elastic.co/guide/en/elasticsearch/guide/current/synonym-formats.html) I think we can achieve this using `"Neandertal,Neanderthal"` ?

**Comment by franksc** [comment]
Done with https://github.com/modc08/mytardis/pull/10 and modc08/nectar-shell@4990394b8adf084fa939fa0fe362110d69a19883, modc08/nectar-shell@13a44770ca6a116fbdff7525ab82c1bea0d8f7a2 and modc08/nectar-shell@ea98a18cbfcddbde3a47baaac4d3fd14bc355382
