### ISSUE TITLE
Genome browser links should appear for compressed .vcf and .bam files

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#87]
ACAD's real data contains some .vcf and .bam files that have been gzip'd – so filename is foo.vcf.gz rather than foo.vcf.

Because [Datafile.is_genome()](https://github.com/modc08/mytardis/blob/modc08/tardis/tardis_portal/models/datafile.py#L206) only looks for files with extension .vcf or .bam (case insensitive), no buttons to open these files in the external UCSC Genome Browser appear in the OAGR datafile list.

Some testing indicates UCSC Genome Browser can handled gzip (.gz) and bzip2 (.bz2) compressed files, so we should display 'open in genome browser' buttons for .vcf and .bam files with these extensions.

**Comment by Li-ReDBox** [comment]
@franksc, I [commit](https://github.com/modc08/mytardis/commit/90b42e4cf5dfece15d08b1b55daa226dee1e1192)ted a change of above mentioned function. It passed my dummy tests: when correct types present, buttons are shown.

**Comment by franksc** [comment]
:+1:
