### ISSUE TITLE
Restore case-insensitive search

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#88]
Adding support for synonym searching (cf. #85) has made searching case sensitive – so a query for 'cooper' doesn't return expected results whereas 'Cooper' (case-sensitive match for the indexed metadata) does.

@shundezhang is on the case

**Comment by franksc** [comment]
Searching re-tested as result of modc08/nectar-shell@cb1de93c2d6d0d8765c43de9158f5f5753ba7c1f and appears to work as before (expected results retrieved / nothing weird), including desired synonym searching.

**Comment by shundezhang** [comment]
... and this commit modc08/mytardis@c23281c9f0ddad071d713ca99f95998a62a4bdd0
