### ISSUE TITLE
Optimisation for source-heavy views

### ISSUE THREAD

**Issue by franksc** [modc08/modc08#89]
@craigpatten raised the noticeably slow loading of OAGR views which contain many sources – namely the Source index page and the OAGR home page, which loads all sources to populate them on the map. Some testing with [django-debug-toolbar](https://github.com/django-debug-toolbar/django-debug-toolbar) shows a horrifying number of individual SQL queries for these views.

The main pain point seems to be the call of [Source.get_datasets()](https://github.com/modc08/mytardis/blob/modc08/tardis/apps/acad/models.py#L84) for each source object in the database to lookup if the source is associated with a dataset the end user can see for their level of authentication, and only show sources that fall into this category. (This is not just a nicety for end users – showing sources associated with a dataset the end user can't see could expose potentially sensitive details about a currently non-public study.) Because there is no direct relationship between datasets and sources the query needs to traverse many tables (dataset, analysis ... sample, source) to look up required data. With 130-odd sources in the current body of data, this means many expensive and slow queries.

One idea that occurs to me is creating a SQL VIEW containing the results of the dataset → source query, and modifying .get_datasets() to use Django's [.raw()](https://docs.djangoproject.com/en/1.5/topics/db/sql/#performing-raw-queries) to query this view directly rather than using the Django ORM.

@craigpatten @shundezhang @Li-ReDBox I am open to all brilliant ideas ...

**Comment by franksc** [comment]
There may also be some applicable wisdom in Django docs [Database access optimization](https://docs.djangoproject.com/en/1.5/topics/db/optimization/) guide

**Comment by Li-ReDBox** [comment]
@franksc, in terms of individual SQL queries, [here](https://docs.djangoproject.com/en/1.5/ref/models/querysets/#when-querysets-are-evaluated) says "Internally, a QuerySet can be constructed, filtered, sliced, and generally passed around without actually hitting the database. No database activity actually occurs until you do something to evaluate the queryset.". Does Source.get_database behaviour differently or I missing something?

**Comment by shundezhang** [comment]
It is a lot faster now. Pls see https://query-test.oagr.org.au/

and the debug toolbar adds some overhead. Disabling the debug toobar is somewhat faster than enabling it.

**Comment by franksc** [comment]
Now much faster with https://github.com/modc08/mytardis/commit/709aa7846a2ef91f3ee41ec7fb75137b339f0847. :+1:
